### ISSUE TITLE
String index out of range error while calling variants from the transcriptome 

### ISSUE THREAD

**Issue by jeaahakobyan** [AstraZeneca-NGS/VarDictJava#268] opened 2019-10-15 14:12 UTC
Hi there,
I'm applying VarDict to transcriptome data from GTEx and get the following error.
```
There was Exception while processing record on H7G88ADXX140313:2:1105:3231:57864 on region 1:27623851-27631000. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: 15
        at java.lang.String.charAt(String.java:658)
        at com.astrazeneca.vardict.modules.CigarParser.prepareSVStructuresForAnalysis(CigarParser.java:2031)
        at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:322)
        at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:89)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
        at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
        at com.astrazeneca.vardict.modes.SimpleMode.access$000(SimpleMode.java:29)
        at com.astrazeneca.vardict.modes.SimpleMode$VardictWorker.call(SimpleMode.java:86)
        at com.astrazeneca.vardict.modes.SimpleMode$VardictWorker.call(SimpleMode.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
VarDictJava fails (there were 11 continued exceptions during the run).
Critical exception occurs on region: 1:27623851-27631000, program will be stopped.
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: 15
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
        at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
        at com.astrazeneca.vardict.modes.SimpleMode.access$000(SimpleMode.java:29)
        at com.astrazeneca.vardict.modes.SimpleMode$VardictWorker.call(SimpleMode.java:86)
        at com.astrazeneca.vardict.modes.SimpleMode$VardictWorker.call(SimpleMode.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```
${vardict_path}/VarDict  -th 20 -G $ref_fasta -f ${AF_THR} -x 1000 -N ${sampleID} -b ${base_name}".bam"   -c 1 -S 2 -E 3 -g 4  /path/to/VarDict/hg19_5k_150bpOL_seg.txt |     ${vardict_path}/teststrandbias.R ${vardict_path}/var2vcf_valid.pl -N ${sampleID} -E -f  ${AF_THR} >   ${base_name}".vardict.vcf"
```
The read which apparently causes the problem:
```
H7G88ADXX140313:2:1105:3231:57864       163     1       27630161        255     63S13M  =       276315301445     CCGCAGTAGCGGAACTGATAGTCGTAGCTTCGCTCCCGCAGCACCATTTCATCCTCTGAGATGGAGCCGCAAGGAC    @CCFFFFFAHFDFIEDCFHGCHIGII1FFHG@F)?FH:A'5@(@G6=CHHECDFBD>@CAC3;A>=?@288=6?AA     NH:i:1  HI:i:1  AS:i:86 nM:i:0  MD:Z:13 NM:i:0   RG:Z:H7G88.2
H7G88ADXX140313:2:1105:3231:57864       83      1       27631530        255     76M     =       27630161-1445    CCTTCTTCATCTGGGAAAAGGAGACCACCAACCTGGTCCGTGTGCTCCAAGGGGATGAGTCCATTGTCAACTGCCT    ADCCCAEFFFFFCHFHHHHJIIIIJIJJIIHJJJHJIJJIIIEIJJJJJJJJJJIIHIJJJJJHHGHHFFFFFCCC     NH:i:1  HI:i:1  AS:i:86 nM:i:0  MD:Z:76 NM:i:0   RG:Z:H7G88.2
```

**Comment by PolinaBevad** [comment] 2019-10-16 07:09
Hi @jeaahakobyan ,

Sorry that you have the issue!

I think I know what the problem is, some reads contain a small matched region, so we have to add a condition to check this. Can you share also the part of the BAM file from this region? I see that there are other reads where the problem can occur (`there were 11 continued exceptions during the run`). So it's better if l check all of them. You can send it to me by email at polina_bevad@epam.com
Thank you!

**Comment by jeaahakobyan** [comment] 2019-10-16 08:11
Hi Polina,
Thanks for the prompt follow-up. Sure, will send the region. 
Thanks

**Comment by PolinaBevad** [comment] 2019-10-17 08:47
Hi Anna,
The fix for this bug is prepared: https://github.com/AstraZeneca-NGS/VarDictJava/pull/269 
You can use this branch if the problem is critical for your environment because we do not create releases very often... 
Let me know if the will be any problems!

**Comment by jeaahakobyan** [comment] 2019-10-21 07:25
Hi Polina,
Thanks for the quick fix. It runs smoothly now.
Cheers

**Comment by PolinaBevad** [comment] 2019-10-28 06:47
Hi Anna, thank you! The fix was merged in master, so it will be in the next release.
I'll close the issue.

**Closed by PolinaBevad** 2019-10-28 06:47 UTC
