### ISSUE TITLE
Where to find the header of 55 columns of VarDcit 

### ISSUE THREAD

**Issue by HeXY0515** [AstraZeneca-NGS/VarDictJava#163] opened 2018-11-01 08:13 UTC
Hi,
I run ./VarDict with -h option, but the output file has 55 columns and at the 27th column(MIS_NT) there is negtive value(-1), which results in error with fiser-tesr in next step: testsomatic.R. 
Could you please added the  complete header?

**Comment by PolinaBevad** [comment] 2018-11-01 10:46
@HeXY0515, hello!
Sorry, that you have the issue with VarDict!
 
27-th column contains the variant coverage for the variant in the second sample.
We will add description of fields for somatic mode in the documentation and in the header, but it is strange, that you have the error. What version of VarDict do you use? In VarDictJava 1.5.7 we have the adjustment, that must fix such situations. 

Could you please provide small part of BAM file and the region where this error appears so we could test this case? You can send it to polina_bevad@epam.com .

**Comment by HeXY0515** [comment] 2018-11-02 02:04
Hi, PolinaBevad. Thank you. I run the verison 1.5.7(the release VarDict-1.5.7.tar) and I am sure there are negative values at column 27 (a total of 55 columns), and there are only 36 columuns in the header.  Bam files of regon "chr2:17759851-17765000" contains an error site "chr2:176398406" with the value -1 at 27 column. I have send the bam files(normal and tumor) to your email polina_bevad@epam.com. 
Thanks for your time!

**Comment by HeXY0515** [comment] 2018-11-02 02:09
Hi, PolinaBevad. Thank you. I run the verison 1.5.7(the release VarDict-1.5.7.tar) and I am sure there are negative values at column 27 (a total of 55 columns), and there are only 36 columuns in the header. Bam files of regon "chr2:17634851-17640000" contains an error site "chr2:176398406" with the value -1 at 27 column. I have send the bam files(normal and tumor) to your email polina_bevad@epam.com.
Thanks for your time!

**Comment by HeXY0515** [comment] 2018-11-02 02:59
Hi, PolinaBevad. Thank you. I run the verison 1.5.7(the release VarDict-1.5.7.tar) and I am sure there are negative values at column 27 (a total of 55 columns), and there are only 36 columuns in the header. Bam files of regon "chr2:176394851-176400000" contains an error site "chr2:176398406" with the value -1 at 27 column. Because VarDict in Java and Perl both gives the same results, I have send the bam files(normal and tumor) . the command line and the result files of VatDict in Java and Perl version to your email polina_bevad@epam.com. 
Thanks for your time!

**Comment by PolinaBevad** [comment] 2018-11-02 12:47
@HeXY0515, hello!

I've reproduced this error and found the record where it can be located. 
In my opinion, it is a case of insertion on the record "ST-E00169:101:hcvl3ccxx:6:2208:12520:37208". Count from it must be incremented to coverage of variant G->A on position 176398406, but it is incremented only to the possible variant A&A on 176398405 (it doesn't have "good" quality, so you don't see it in the output).

So the counts of coverage in the second part of the string in output must be zeros (and also the pmean fields and so on), like this: 
`CNIC-02-04-0001-01-WGS-PP-4201	chr2	chr2	176398406	176398406	G	A	30	11	10	7	7	4	G/A	0.3667	2;2	21.9	1	23.8	1	60.0	4.500	0.4286	0	2.4	10	0	4	2	0	0	0;0	0	0	0	0	0	0	0	0	0	0	0	0	12.000	1	ACCTGGGTTCGATTATTTGG	AAAAAAAAAAAAGGCCCATG	chr2:176394852-176400000	LikelySomatic	SNV	0	0	0	0`

We will fix it, but it can spend some time to find a better solution for such cases, so for now, you can replace negative values in column 27 to 0 (you can do it by awk utility). 
Sorry that you have this problem. I will comment on the issue when we will merge PR with the fix. Headers will be also added.

**Comment by HeXY0515** [comment] 2018-11-03 12:53
@PolinaBevad, Thanks for the replying and I can replace the negative values in column 27. Thanks agian and hope for the good news.

**Comment by PolinaBevad** [comment] 2019-02-22 09:14
Xiaoyu, hello!
I will close this issue because the fix is already merged in master: negative value was fixed and now all columns are outputted in the header. This fix will be included in the future release. 
If you want to use the new version of VarDictJava before our release, you can build it as described here: https://github.com/AstraZeneca-NGS/VarDictJava#compiling 
Thank you!

**Closed by PolinaBevad** 2019-02-22 09:14 UTC
