### ISSUE TITLE
1.5.6: NullPointerException in joinVariantWithNM

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#153] opened 2018-10-15 13:43 UTC
Polina, Zhongwu, Pablo and all;
While testing the 1.5.6 release we ran into a null pointer exception in two different samples:
```
Exception in thread "main" java.lang.NullPointerException
        at com.astrazeneca.vardict.variations.Variant.joinVariantWithNM(Variant.java:418)
        at com.astrazeneca.vardict.VarDict.somdict(VarDict.java:740)
        at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:432)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:307)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:72)
        at com.astrazeneca.vardict.Main.run(Main.java:153)
        at com.astrazeneca.vardict.Main.main(Main.java:31)
```
Here is a small standalone test case that reproduces the problem:

https://s3.amazonaws.com/chapmanb/testcases/vardict_joinnm_nullpointer.tar.gz

I know there are some outstanding PRs dealing with NM issues and am not sure if any of those resolve this issue. Please let me know if do an I'm happy to test; likewise let me know if any other information to debug this would be helpful.

**Comment by chapmanb** [comment] 2018-10-15 17:42
Polina;
Thanks for this investigative work. I've been running more validations and it sounds like we should be getting #152 and also #139 integrated for a new release. The StrongLOH problem in #139 appears pretty commonly with paired output in 1.5.6; coupled with the poor way in which testsomatic.R just swallows errors this will cause essentially empty VCFs whenever there is a problem StrongLOH with 45 columns, which seems to happen pretty frequently.

I'd like to also remove the general try catch in testsomatic.R which swallows errors. We'd had a fix for this previously but it appears to have gotten reverted.

https://github.com/AstraZeneca-NGS/VarDict/commit/2e21e02e621b61a56cb0b8d5253023c10b3e67d5

Zhongwu, Pablo and all. What do you think about this progress towards a new release?

**Comment by PolinaBevad** [comment] 2018-10-23 09:36
@chapmanb, hello!
The NPE now won't be reproduced since 1.5.7, thank you a lot for finding it!
Also, thank you for the changes in testsomatic.R script.
I'll close the issue.

**Closed by PolinaBevad** 2018-10-23 09:36 UTC
