### ISSUE TITLE
Number of columns

### ISSUE THREAD

**Issue by dattam** [AstraZeneca-NGS/VarDictJava#141] opened 2018-09-26 21:32 UTC
The latest version of VarDict is producing 36 columns as opposed to 34. This might need to be fixed.

On a separate note: A similar issue was raised in "VarDict" and the quick-fix suggested was to add ' || mynumcols == 36' to the code. However, the mapping of colClasses also seems to be inaccurate. Wondering if there is a simple short term fix. For example, can we 'cut' out the newly added columns and make the vardict output compatible with downstream scripts ? If so, can some one help me to identify the columns to "cut" out. Thanks!

if (mynumcols == 34 || mynumcols == 38){ # 34 columns for standard bed files, 38 for amplicon mode
    d <- read.table( textConnection(myinput), sep = "\t", header = F, colClasses=c("character", NA, NA, NA, NA, "character", "character", NA, 
NA, NA, NA, NA, NA, "character", NA, NA, NA, NA, NA, NA, NA, NA), col.names=c(1:mynumcols))
} else if (mynumcols > 0){
    stop("Incorrect input detected in teststrandbias.R")
}

**Comment by PolinaBevad** [comment] 2018-09-27 06:14
@dattam, hello!
Sorry you have an issue with this.
The correct number of columns for output in simple mode is 36. There are two columns (35 and 36) that were added to support structural variants and duprate. You can cut them, if you don't use SVs in analysis, but it is better to use the updated scripts from VarDict Perl repository. The problem is that submodule in this project usn't updated to the last version of VarDict perl repository. You can use the version of scripts directly from  https://github.com/AstraZeneca-NGS/VarDict. We will update a link to it from current repository.

We will look closer to the mapping, but as I see now, it mustn't produce any errors, if you use R script for 36 columns, because additional columns in teststranbias.R are calculating for columns, that are in current mapping. Do you have errors while using it?

**Comment by PolinaBevad** [comment] 2018-10-18 12:48
@dattam, hello!
We updated scripts for .R in release 1.5.7 (we also fixed .pl scripts for somatic mode there).
Mapping of the columns isn't important because only 4 columns from it (#10-13 that map correctly) are necessary for the calculating in fisher.test.
I will close this issue, please, re-open it, if you will have any additional questions.

**Closed by PolinaBevad** 2018-10-18 12:48 UTC
