### ISSUE TITLE
Seemingly incorrect AMPBIAS flag added to indel

### ISSUE THREAD

**Issue by jamie-a** [AstraZeneca-NGS/VarDictJava#94] opened 2018-01-19 14:19 UTC
Hi there,

I'm running in amplicon aware mode with the appropriate bed file and I'm having an issue where a variant is being flagged as having amplicon bias even though there is only a single amplicon covering it.

The bed file for the region is:

chr13	32931739	32932002	BRCA2	0	.	32931766	32931978
chr13	32931857	32932127	BRCA2	0	.	32931884	32932103
chr13	32936555	32936831	BRCA2	0	.	32936581	32936806

And here is the VCF call:

chr13	32932023	.	ATA	TT	248	AMPBIAS	SAMPLE=XXX;TYPE=Complex;DP=203;VD=84;AF=0.4138;BIAS=1:1;REFBIAS=0:102;VARBIAS=0:84;PMEAN=47;PSTD=1;QUAL=38.9;QSTD=1;SBF=1;ODDRATIO=0;MQ=60;SN=168;HIAF=0.4242;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=0.5;HICNT=84;HICOV=198;LSEQ=TGGCTGATGGTGGATGGCTC;RSEQ=CCCTCCAATGATGGAAAGGC;GDAMP=1;TLAMP=1;NCAMP=0;AMPFLAG=1	GT:DP:VD:AD:AF:RD:ALD	0/1:203:84:102,84:0.4138:0,102:0,84

In IGV you can see that it's close to another amplicon (as you can tell from the bed file coords) but it doesn't overlap. This variant has been previously validated and is important so I'm somewhat concerned as to why it is being flagged.

![screenshot from 2018-01-19 14 16 01](https://user-images.githubusercontent.com/26119320/35154763-5b60e3e2-fd23-11e7-9b42-5621a5c96829.png)

**Comment by jamie-a** [comment] 2018-02-12 15:08
Hi @mjafin I just wondered if anyone is looking into this issue?

**Comment by jamie-a** [comment] 2018-05-14 15:48
Any update on this at all @mjafin ? I'm happy to provide more information if needed.

**Comment by PolinaBevad** [comment] 2018-05-15 12:08
Hello @jamie-a,
Could you please send the part of bam file with this region to polina_bevad@epam.com? I will try to find the cause of this behavior.

**Comment by jamie-a** [comment] 2018-05-15 12:51
Shall do, thanks Polina.

**Comment by PolinaBevad** [comment] 2018-05-17 09:14
Hello @jamie-a ,
I received your data and reproduced the issue. 

It looks like there are some problems in multi-allelic cases. There was a fix in VardictJava to support multi-allelic site here (https://github.com/AstraZeneca-NGS/VarDictJava/commit/bc9cd4b85d3c1f81a7bc32bea74160d9e729e3ae), so some logic differs from perl version. Perl uses only first allele and AMPFLAG will be 0. So maybe we must change the logic to determine this flag too.

If this issue is critical for your research you can use perl version until we fix it in Java version.

**Comment by PolinaBevad** [comment] 2018-11-12 09:13
@jamie-a, hello!
We fixed the error with AMPFLAG in VarDictJava 1.5.8. for the multi-allelic case. Now the flag will be set only if good variants on the position between different amplicons differ. Before in multi-allelic case, the flag worked if good variants on the position on one amplicon differed (i.e. in every case when we have few good variants on position).

I will close this issue. You can reopen it if you have any questions.

**Closed by PolinaBevad** 2018-11-12 09:13 UTC
