### ISSUE TITLE
VarDictJava not reporting EGFR variant, perl version does

### ISSUE THREAD

**Issue by mjafin** [AstraZeneca-NGS/VarDictJava#102] opened 2018-03-19 13:06 UTC
[L861Q_chr7_55259523-55259525.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/1825040/L861Q_chr7_55259523-55259525.zip)

See difference between:
```
vardict.pl -G /path/to/hg19.fa -f 0.001 -N abc -c 1 -S 2 -E 3 -g 4 -b L861Q.bam -R chr7:55259523-55259525
```
and
```
vardict-java -G /path/to/hg19.fa -f 0.001 -N abc -c 1 -S 2 -E 3 -g 4 -b L861Q.bam -R chr7:55259523-55259525
```

**Comment by PolinaBevad** [comment] 2018-03-21 13:33
@mjafin, hello!
The reason of difference between perl and java is the change from this commit: https://github.com/AstraZeneca-NGS/VarDictJava/commit/feb1c2f480277ca8101ec633b4307c01e8126258
This solution was discussed in issue **Handling of overlapping reads from short inserts** #60. 

The case for this variation is: almost all mates for the reads on this position are overlapping, so the CIGAR processing is stopped for them and their counters aren't taken in account. As a result, bias (that counted with forward and reverse counters) becomes "2;1", freq < 0.25 and this variation doesn't pass through the "good" variation filter for SNV's. 

Counters in perl: fwd: 111, rev: 127, bias flag: 2, freq: 0.2416
Counters in java: fwd: 3, rev: 127, bias flag: 1, freq: 0.2317

As said in issue above, this solution was faster than forming a consensus. The second condition for the filtering variants is frequency. For example, this variant's frequency is a bit less then threshold for the frequency. What if we decrease it or make it an option for SNV only?

**Comment by mjafin** [comment] 2018-03-21 13:36
Thanks for getting to the bottom of this @PolinaBevad. Let's have a collective think about the best way forward as clearly the current approach is not detecting bias correctly.

**Comment by mjafin** [comment] 2018-03-21 13:53
I wonder if we changed the logic of the algorithm to use R1 instead of strand? My thinking is that R1 and R2 should be randomly / evenly aligning to either strand. Any flaws in my thinking? 

So in effect (e.g.) R1 would always be read completely and R2 would only be read for the part where it doesn't overlap with R1

**Comment by chapmanb** [comment] 2018-03-21 13:57
Miika, thanks for spotting this. Polina -- thanks for this detective work and identifying the underlying issue. Is it possible to have a random assignment of CIGAR trimming to the forward or reverse strands for overlaps so we don't introduce apparent bias? There would still be some decrease in frequency relative to consensus building, but it would resolve the most apparent change.

(while I'm writing, looks like Miika had a similar idea with R1/R2 based "randomization")

**Comment by mjafin** [comment] 2018-03-21 14:17
My thinking is that however we pseudo-randomise the process it needs to be reproducible and not based on any random number generator (i.e. two subsequent runs should produce the same result). One of the following might work:
- R1 vs R2
- Sum of read name ascii numbers with processing of forward strand for even result and reverse strand for odd result 
- Something else...

**Comment by chapmanb** [comment] 2018-03-21 15:27
Miika -- being reproducible makes sense, but we should be able to do with random removal by setting a consistent seed to whatever we use for the randomization. That should hopefully be more straightforward than relying on something external for pseudo randomization.

**Comment by mjafin** [comment] 2018-03-21 15:54
From @zhongwulai:
```
Yes, R1/R2 can solve this problem, but might lose the ability to detect real strand biased variants.

Maybe change it to an option, and only trigger R1/R2 when option is set.
```

**Comment by PolinaBevad** [comment] 2018-09-05 16:39
@mjafin, hello! Can we close this issue or there are other questions on this topic?
Both types of skipping reads (by R1/R2 and by forward/reverse) were implemented and the test case for this situation was added.

**Comment by mjafin** [comment] 2018-09-06 12:50
Yes OK by me.

**Comment by PolinaBevad** [comment] 2018-09-06 13:10
@mjafin, thanks, I close the issue.

**Closed by PolinaBevad** 2018-09-06 13:10 UTC
