### ISSUE TITLE
Compilation issue: generating Javadoc for Version 1.5.6

### ISSUE THREAD

**Issue by mezewudo** [AstraZeneca-NGS/VarDictJava#156] opened 2018-10-17 15:35 UTC
The compilation fails at the point of generating Javadocs.

I have tried this on two separate machines but still get the same error:

Task: javadoc FAILED.

Please take a look.

**Comment by PolinaBevad** [comment] 2018-10-18 11:32
@mezewudo, hello!
Sorry, you have the issue with it.

I tried to run it with commands `./gradlew clean javadoc` , `./gradlew javadoc` and the task `javadoc` through the Gradle interface in Intellij Idea and all tasks completed successfully. 
Could you please specify the command that you use and the versions of OS, JDK and Gradle (if you don't use wrapper) where the error appears?

**Comment by PolinaBevad** [comment] 2018-10-18 13:44
@mezewudo, thank you. 
I reproduced the error on the other system, we will fix these javadoc errors, most of them are because of symbols '<' and '>' describing structural variants.  
Thank you for reporting this, I will comment this issue when we merge the fix.

**Comment by PolinaBevad** [comment] 2018-11-26 10:52
@mezewudo , hello!
I will close this issue because the problem was fixed. We also added the step to build javadoc in Travis CI.

**Closed by PolinaBevad** 2018-11-26 10:52 UTC
