### ISSUE TITLE
Error when local realignment is turned off:

### ISSUE THREAD

**Issue by ltfang-bina** [AstraZeneca-NGS/VarDictJava#15] opened 2015-06-15 23:50 UTC
This produces an error (used -k 0 to turn off local realignment):
VarDict -G human_g1k_v37_decoy.fasta -f 0.01 -h -b 'tumor.k.bam|normal.k.bam' -k 0 -Q 1 -c 1 -S 2 -E 3 -g 4 1.k.bed

The error message is:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 101
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:2194)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2536)
	at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:356)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:251)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:67)
	at com.astrazeneca.vardict.Main.run(Main.java:145)
	at com.astrazeneca.vardict.Main.main(Main.java:25)

This runs without a problem (default, so local realignment is on):
VarDict -G human_g1k_v37_decoy.fasta -f 0.01 -h -b 'tumor.k.bam|normal.k.bam' -Q 1 -c 1 -S 2 -E 3 -g 4 1.k.bed

The data are stored here:
https://drive.google.com/folderview?id=0B9pfRlnkG-Z7fnAwUzFvYllnOGpOODNIdUdCaVI5Z1hRcl9zYi1vVmFTN0o4bURrelJHZlk&usp=sharing

**Comment by vkirst** [comment] 2015-06-17 14:53
It looks like the problem is in the original algorithm.

stderr out from perl-script:

`substr outside of string at ./vardict.pl line 1186, <SAM> line 1159.
Use of uninitialized value $s in string eq at ./vardict.pl line 1187, <SAM> line 1159.
substr outside of string at ./vardict.pl line 1191, <SAM> line 1159.
Use of uninitialized value in ord at ./vardict.pl line 1191, <SAM> line 1159.
substr outside of string at ./vardict.pl line 1198, <SAM> line 1159.`

We will consult with Zhongwu Lai to clarify this issue.

**Comment by zhongwulai** [comment] 2015-06-18 03:37
For some reason, I couldn't download the bam files.  Other files are fine, including index .bai files.  Can you send bam files to me directly if they're not too big?

**Comment by ltfang-bina** [comment] 2015-06-18 03:41
Yep, here you go.

Thanks.


*-- Li Tai Fang, PhD  *//  Bioinformatics Scientist, Bina Technologies,
part of Roche Sequencing

E. ltfang@bina.com   //   Tel. +1.650.779.4564

*Learn More*  //  video <http://www.bina.com/product.html>  //  news
<http://www.bina.com/press-coverage.html>  //  posters
<http://info.bina.com/posters>  //  science
<http://www.bina.com/science.html>  //  platform
<http://www.bina.com/platform.html>

**Comment by zhongwulai** [comment] 2015-06-18 17:02
I don't see the substr outside of string warning message in the latest Perl version.  I got a different benign warning that's specific in paired mode, which can be easily fixed with one line of code.  Can you take a look again at Java version?  I'll have a push with some updates on realignment at >= 3 MNP.  This example has 4 MNP.

**Comment by vkirst** [comment] 2015-06-19 11:49
I pulled the last perl version and was able to reproduce the issue using ‘-k 0’ option.

**Comment by zhongwulai** [comment] 2015-06-19 19:52
OK, found the bug.  Need to move line 968 '$ci +=4;' below line 973.  $ci got incremented one step too early.

I also made a few updates to prevent local realignment altogether, as there're still a few places performing such tasks even with '-k 0'.

**Closed** 2016-03-07 13:09 UTC
