### ISSUE TITLE
Calling Fusions

### ISSUE THREAD

**Issue by crispgc** [AstraZeneca-NGS/VarDictJava#248] opened 2019-08-07 14:08 UTC
Hi there,
I've been using VarDict for a while and so far it has been great at detecting SNPs and indels, accurate and fast, so.. congratulations for that.

Now I'm experimenting with Structural Variant calling and I'm losing very clear translocations happening between different chromosomes. This is rare because deletions and duplications happening in the same chromosome are being called without any issue, but not the other ones.

Is there any known bug that is making this happen?
Thanks in advance!
Cris

**Comment by PolinaBevad** [comment] 2019-08-09 12:58
Hi Cris,
Sorry that you have the issue while using VarDict!

I guess that the issue is that we don't determine translocations between chromosomes now. VarDict was designed to work separately on each BED region (and so it doesn't hold in memory regions from different chromosomes). INV, DUP and DEL are within the same chromosome, so there are no problems with them.

Perhaps you can share part of the sample where you see these translocations, so we can think about the way to find them? The screenshots from the genome browser where you see them will also be useful.

**Comment by PolinaBevad** [comment] 2019-10-10 14:20
Hi Cris, 
I will close the issue because there was no answer from you. But if it is relevant, please, re-open it!
Thank you!

**Closed by PolinaBevad** 2019-10-10 14:20 UTC
