### ISSUE TITLE
Java crashes when VarDict file modified to do profiling with hprof

### ISSUE THREAD

**Issue by alexanderwhatley** [AstraZeneca-NGS/VarDictJava#43] opened 2016-05-26 04:17 UTC
I am trying to profile VarDictJava by modifying the DEFAULT_JVM_OPTS in the file build/install/VarDict/bin/VarDict to '"-Xrunhprof:cpu=times,depth=10" "-Xmx768m"'. However, when I try running the software, Java itself crashes, and I get the error message 
# A fatal error has been detected by the Java Runtime Environment:
# 
# SIGSEGV (0xb) at pc=0x00007fb87dcdfc0c, pid=41165, tid=140429174187776
# 
# JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x80ec0c]  os::PlatformEvent::unpark()+0x1c
# 
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# 
# An error report file with more information is saved as:
# /gpfs01/home/kpbh388/tests/VarDictJava/build/install/VarDict/bin/hs_err_pid41165.log
# 
# If you would like to submit a bug report, please visit:
# http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
# 

Aborted (core dumped)

The log file is attached. Thanks for your help.

[hs_err_pid41165.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/283454/hs_err_pid41165.txt)

**Comment by NataliaLeznikova** [comment] 2018-01-26 12:32
Hello,@alexanderwhatley!

Unfortunately we couldn’t reproduce the error, but we found that ‘cpu=times’ argument of ‘-Xrunhprof’ option often leads to many application's crash, not only VarDict. That is why it seems that the problem is not in the VarDict application, but in the profiler.

If this is not the case, please share VarDict launch options: what parameters have you used and what files tried to process (the size is important).

Thanks!

**Comment by PolinaBevad** [comment] 2018-09-10 09:50
@alexanderwhatley, hello!
I will close the issue because the problem could not be reproduced in our environment, incl. Java 7.0.45 and higher, and there was no information about the command you use to run VarDict. 
We recommend using VarDictJava on Java version 8 and higher. The possible cause of the issue are the profiler bugs. Hprof utility was removed since JDK 9 due to problems with it (JEP 240), please try any other profiler (JProfiler, YourKit or JFR). If the problem appears again, please reopen the issue.

**Closed by PolinaBevad** 2018-09-10 09:50 UTC
