### ISSUE TITLE
repeat variants lines

### ISSUE THREAD

**Issue by JunyanZH6** [AstraZeneca-NGS/VarDictJava#226] opened 2019-05-16 03:21 UTC
Hi 

I run VarDict with command:
VarDict -G ${ref_file} -f $AF_THR -N "$sample" -b $MKDUP_OUT_DIR/${sample}.mkdup.bam -z -c 1 -S 2 -E 3 -th ${nt} ${target_file} | \
 teststrandbias.R | \
 var2vcf_valid.pl -N ${sample} -E -f $AF_THR >${OUT_DIR}/${sample}_Filtered.vcf

I found that the output file “${sample}_Filtered.vcf” have repeat variants lines like this:
10	29578084	.	A	G	228	PASS	SAMPLE=TS449N;TYPE=SNV;DP=74;VD=74;AF=1;BIAS=0:2;REFBIAS=0:0;VARBIAS=43:31;PMEAN=46.1;PSTD=1;QUAL=36.8;QSTD=1;SBF=1;ODDRATIO=0;MQ=50.4;SN=148;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.0;HICNT=74;HICOV=74;LSEQ=GAGCTGCCTGTCACCGACTA;RSEQ=GTGGAGCAGTGTTTCTTCCG;DUPRATE=0;SPLITREAD=0;SPANPAIR=0	GT:DP:VD:AD:AF:RD:ALD	1/1:74:74:0,74:1:0,0:43,31
10	29578084	.	A	G	228	PASS	SAMPLE=TS449N;TYPE=SNV;DP=74;VD=74;AF=1;BIAS=0:2;REFBIAS=0:0;VARBIAS=43:31;PMEAN=46.1;PSTD=1;QUAL=36.8;QSTD=1;SBF=1;ODDRATIO=0;MQ=50.4;SN=148;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.0;HICNT=74;HICOV=74;LSEQ=GAGCTGCCTGTCACCGACTA;RSEQ=GTGGAGCAGTGTTTCTTCCG;DUPRATE=0;SPLITREAD=0;SPANPAIR=0	GT:DP:VD:AD:AF:RD:ALD	1/1:74:74:0,74:1:0,0:43,31

Is it normal for repeat variants lines? Why happen to this? 

Thanks!
JY

**Comment by PolinaBevad** [comment] 2019-05-16 11:48
@JunyanZH6, hello!

Probably it is a bug because `var2vcf_valid.pl` script must skip duplicated lines. Could you please share the result of the raw VarDict output, i.e. the result from this part of command?
`VarDict -G ${ref_file} -f $AF_THR -N "$sample" -b $MKDUP_OUT_DIR/${sample}.mkdup.bam -z -c 1 -S 2 -E 3 -th ${nt} ${target_file} > output.var`
Duplicates in this step can appear if variants were found in the overlapping regions, but at the next steps, they must be processed and skipped if they meet.
You can delete repeated lines by awk, but it will be great if you can share the file to debug this problem.
Thank you!

**Comment by JunyanZH6** [comment] 2019-05-17 04:19
Hi,
I run analysis step by step with following command:

VarDict -G ${ref_file} -f $AF_THR -N "$sample" -b $MKDUP_OUT_DIR/${sample}.mkdup.bam -z -c 1 -S 2 -E 3 -th ${nt} ${target_file} >${OUT_DIR}/${sample}_Raw.var
No duplicate lines found in output

 teststrandbias.R <${OUT_DIR}/${sample}_Raw.var >${OUT_DIR}/${sample}_Raw.strandbias.var
No duplicate lines found in output

 var2vcf_valid.pl -N ${sample} -E -f $AF_THR ${OUT_DIR}/${sample}_Raw.strandbias.var >${OUT_DIR}/${sample}_Filtered.vcf
Some duplicate lines found in output

I think duplicate lines probably are caused by filtering step <var2vcf_valid.pl>. It need to further debug.

**Comment by PolinaBevad** [comment] 2019-05-17 07:58
@JunyanZH6, hello!

Could you please clarify do you use the last version of var2vcf_valid.pl script (i.e. from master branch)? A duplicate skip was added in February 2017, but perhaps for some reason, you have an old version of this script.
If it is possible, can you share this Raw.var file for debugging? You can also send it to my email polina_bevad@epam.com

**Comment by JunyanZH6** [comment] 2019-05-29 03:07
Hi 
Thank you for your kind support. 
I checked my script var2vcf_valid.pl, and it is the same with the script in the following link https://github.com/AstraZeneca-NGS/VarDict/blob/2a0fda38b280d3e9624ca02b87c681658f96467a/var2vcf_valid.pl

I am sorry I can’t share my Raw.var file due to data privacy.
Now I just deleted the repeat lines for downstream analysis.

Thanks a lot

**Comment by PolinaBevad** [comment] 2019-05-29 07:52
@JunyanZH6, thank you for the reply!

Okay, I tried to repeat it on public data and I've found the cause. It appears due to skipping of the structural variant that isn't fit the criteria by read support. I've created a PR in Perl repository to fix this, but you can change `var2vcf_valid.pl` script with this version if needed: 
https://github.com/AstraZeneca-NGS/VarDict/pull/112/files
Thank you for finding this!

**Comment by JunyanZH6** [comment] 2019-05-30 04:10
Hi
Thanks for your help!
I used the fixed script var2vcf_valid.pl you provided. The repeat variants lines are removed.
But I found another difference compared with previous results repeat lines included.

The VCF header from previous results repeat lines included
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele Frequency">
The VCF header from new results no repeat lines included
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">

Why it is changed for this?
Best,
Junyan

**Comment by PolinaBevad** [comment] 2019-05-30 07:43
@JunyanZH6, hello!

Great, thank you for checking this!
The AF tag was changed in this PR to support VCF 4.3 specification: https://github.com/AstraZeneca-NGS/VarDict/pull/94

**Comment by PolinaBevad** [comment] 2019-06-04 09:42
Junyan, hello!

I will close this issue because it was resolved. Let me know if you have any other questions!
Thank you!

**Closed by PolinaBevad** 2019-06-04 09:42 UTC
