### ISSUE TITLE
missed variant call in 1 out of 3 replicates

### ISSUE THREAD

**Issue by kjass001** [AstraZeneca-NGS/VarDictJava#147] opened 2018-10-04 10:19 UTC
Hi,
We have a discordance issue and we just can't find the reason. Can anyone help us out?
We tested 3 clinical samples (same DNA extract) in one sequencing run. 
In 2 of the 3 samples there is (an expected) call of TP53 E343* (NM_000546.5) (genomic position: 17: 7,574,000 C>A).
In one sample (1808-02528-2) this variant is not called by VardictJava -however, the mismatch is present in the .bam (bwa-mem aligner). The variant is close to the 3' end of the amplicon and in the sample where the variant is missed, we see a strong coverage drop in the adjacent amplicon. Do we miss an option to correct for this?

The commandline for Vardict we use:
vardictcmd = '/home/sam/Scripts/VarDictJava/build/install/VarDict/bin/VarDict -G /home/sam/Downloads/hg19.fa -f ' + AF_THR + ' -N ' + samplename + ' -th ' + threads + ' -b ' + filepath + ' -z -c 1 -S 2 -E 3 -g 4 -r 5 ' + bedfile + ' | /home/sam/Scripts/VarDictJava/VarDict/teststrandbias.R | /home/sam/Scripts/VarDictJava/VarDict/var2vcf_valid.pl -N ' + samplename + ' -E -A -f ' + AF_THR + ' > ' + outvcfpath 

A screenshot of the .bam files in attachment.
![2018-10-04 12_15_06-_project - golden helix genomebrowse 3 0 0](https://user-images.githubusercontent.com/39410349/46467968-b2116c00-c7be-11e8-80dc-7fc6abb84bdd.png)

**Comment by PolinaBevad** [comment] 2018-10-04 14:49
@kjass001 , hello!
Sorry that you have this issue.

Could you please test this region with `-p` option? It makes pileup, so variants won't be filtered by inner filters of VarDict for frequency and the minimum number of variance reads. Does it appear with this option?

If it is possible, could you please send the small part of bam file with this region to us for testing? You can do it by email polina_bevad@epam.com. We have the bug in amplicon analysis (#94) that will be fixed after critical issues, so we can test if it will also fix your problem.

**Comment by PolinaBevad** [comment] 2018-11-16 09:36
@kjass001 , hello!
You wrote me an email about a month ago, that you will send the bam files to reproduce this issue. Do you have this problem, or it is disappeared on the last version? If the error still appears, you can send me data to check this case.

**Comment by PolinaBevad** [comment] 2019-02-19 15:56
@kjass001, I will close the issue, because there was no answer from you. 
You can reopen it if the error repeats or you will have some additional information on the issue.

**Closed by PolinaBevad** 2019-02-19 15:56 UTC
