### ISSUE TITLE
Exception :  java.lang.NumberFormatException: For input string: "-?" with realignment 

### ISSUE THREAD

**Issue by HeXY0515** [AstraZeneca-NGS/VarDictJava#167] opened 2018-11-07 04:22 UTC
Hi, 
There is an error in the verison 1.5.7:
"java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "-?"" 
And the error rised after the site:
"CNIC-02-04-0001-01-WGS-PP-4201  chr13   chr13   35708232        35708232        T       C       48      46      0       0       19      27      C/C     0.9583  0;2     32.9    1       27.1    1       60.0    10.500  0.9767  0       1.5     20      20      0       0       10      10      C/C     1.0000  0;2     39.8    1       26.6    1       60.0    9.000   1.0000  0       1.4     0       2.000   1       ATTCTGTATTTTGAAAGGAA    AATTTAAGTAGATGGTGTTA    chr13:35704852-35710000 Germline        SNV     0       0       0       0"
I am sure it has something with the realignment option(-k), because it is ok when set "-k 0" but it exited when set "-k 1". 
 Does anyone encounter this problem and please let me know if you need the test data. Thanks~

**Comment by PolinaBevad** [comment] 2018-11-07 06:34
@HeXY0515, thank you for reporting this!
Please, can you send the data (bam and region) to my email polina_bevad@epam.com? 
I will check it.

**Comment by PolinaBevad** [comment] 2018-11-07 11:45
@HeXY0515, I reproduced the issue and found that it appears due to mismatches after insertion on position 35713194. 
Could you run this sample with `-X 0` option? It will set the number of mismatches to look after insertion and deletion to zero, so some MNVs can be recognized as few SNVs, but the error must be gone.
 
We will fix this error, it is associated with some changes about MNV that have been added recently.

**Comment by zhongwulai** [comment] 2018-12-11 21:55
@PolinaBevad Have you bottomed this out?  -X 0 is not ideal as it's the main mechanism for VarDict to call complex variants (phasing)?  Can you share the test case bam file?  Thanks!

**Comment by zhongwulai** [comment] 2019-01-03 15:07
@PolinaBevad Yes, you're right.  The root cause is the mistches right before insertions, which is unexpected in BWA, likely due to GATK's local realignment.  I've pushed the fix into the Perl version and committed in github.  Would be great if you can also update the Java version.  This should fix the Issue 163 as well.

**Comment by HeXY0515** [comment] 2019-01-04 06:32
@zhongwulai  @PolinaBevad  Great! Thanks a lot and I guess the java version will be updated soon.

**Comment by PolinaBevad** [comment] 2019-02-22 09:15
Xiaoyu, hello!
I will also close this issue, this fix is merged in master too. 
Thank you!

**Closed by PolinaBevad** 2019-02-22 09:15 UTC
