### ISSUE TITLE
Missing position when running with (-p) and (-k 1)

### ISSUE THREAD

**Issue by roh329** [AstraZeneca-NGS/VarDictJava#265] opened 2019-10-10 06:17 UTC
When I ran VarDict with the pileup (-p) and local realignment(-k 1) option, some positions were missing.

The following example, position chr10:121530513 was missing in the pileup lines.
(Reference: Homo_sapiens_assembly38.fasta)

Option: -p -k 1
```
LHC294_T3       chr10   chr10   121530514       121530514       C       A       348     2       195     150     1       1       C/A     0.0057  2;2     36.0    1       36.0    0       60.0    4.000   0.0058  0       0       1.000   1
       1.0     2       347     CCGCCTATAATCCCAGCTAC    AGGAGGCTGAGGCAGGAGAA    chr10:121520173-121538715       SNV     0       0
LHC294_T3       chr10   chr10   121530515       121530515       A       A       349     0       198     150     0       0       A/A     0       2;0     32.4    1       35.6    1       60.0    696.000 1.0000  0       0       0       0
       0.1     348     348     0       0       chr10:121520173-121538715               0       0
LHC294_T3       chr10   chr10   121530512       121530512       A       A       332     0       187     145     0       0       A/A     0       2;0     32.6    1       35.6    1       60.0    331.000 1.0000  0       0       0       0
       0.1     331     331     0       0       chr10:121520173-121538715               0       0
LHC294_T3       chr10   chr10   121530514       121530515       CA      TCG     556     1       193     150     1       0       CCA/+4  0.0018  2;0     14.0    0       36.0    0       60.0    2.000   0.0029  0       0       0       0
       0       1       346     CCGCCTATAATCCCAGCTAC    GGAGGCTGAGGCAGGAGAAT    chr10:121520173-121538715       Complex 0       2-0-0
```

However, when I turn off local realignment, I can find pileup record at position chr10:121530513.

Option: -p -k 0
```
LHC294_T3       chr10   chr10   121530514       121530514       C       A       348     2       196     150     1       1       C/A     0.0057  2;2     36.0    1       36.0    0       60.0    4.000   0.0057  0       0       1.000   1
       1.0     2       348     CCGCCTATAATCCCAGCTAC    AGGAGGCTGAGGCAGGAGAA    chr10:121520173-121538715       SNV     0       0
LHC294_T3       chr10   chr10   121530515       121530515       A       G       349     1       198     150     1       0       A/G     0.0029  2;0     16.0    0       36.0    0       60.0    2.000   0.0029  0       0       2.000   1
       1.0     1       349     CGCCTATAATCCCAGCTACC    GGAGGCTGAGGCAGGAGAAT    chr10:121520173-121538715       SNV     0       0
LHC294_T3       chr10   chr10   121530512       121530512       A       A       333     0       188     145     0       0       A/A     0       2;0     32.5    1       35.6    1       60.0    332.000 1.0000  0       0       0       0
       0.1     332     332     0       0       chr10:121520173-121538715               0       0
LHC294_T3       chr10   chr10   121530513       121530513       C       CT      346     1       193     150     1       0       C/+1    0.0029  2;0     14.0    0       36.0    0       60.0    2.000   0.0029  0       0       2.000   1
       1.0     1       344     TCCGCCTATAATCCCAGCTA    CAGGAGGCTGAGGCAGGAGA    chr10:121520173-121538715       Insertion       0       0
```

I suppose the insertion variant at chr10:121530513 (C>CT) is combined into the complex variant and did not emit the pileup record.

This is the bam and bed download link of above example. [link](https://drive.google.com/open?id=1ZqQBnbeeP8VfbrNqokDgGGjvo9LR6jHf)

**Comment by PolinaBevad** [comment] 2019-10-16 07:28
Hi @roh329 ,
Thank you for providing the test case! I reproduced the bug and yes, you are right about the reasons: the insertion was combined to the complex and one position was skipped. I'll try to fix it soon.

**Comment by PolinaBevad** [comment] 2019-11-08 06:09
Hi @roh329 , we merged changes that are fixing this issue in the master branch. You can try it and please let me know if everything is okay now.

**Comment by PolinaBevad** [comment] 2019-11-25 06:55
Hi @roh329, I think we can close this issue. Please, reopen it if needed!

**Closed by PolinaBevad** 2019-11-25 06:55 UTC
