### ISSUE TITLE
OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by ReWeda** [AstraZeneca-NGS/VarDictJava#197] opened 2019-03-06 18:24 UTC
Command :
`VarDict -G ~/NAS1/ensemble/GRCh38_p12/Homo_sapiens.GRCh38.dna.primary_assembly.fa -N sample_name -b my.bam -z 1 -c 1 -S 2 -E 3 ~/NAS1/ensemble/GRCh38_p12/Homo_sapiens.GRCh38.dna.primary_assembly.bed > out.vcf`
*(I don't want to pipe the output to downstram analysis scripts)*

Error:
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.String.substring(String.java:1969)
	at com.astrazeneca.vardict.Utils.substr(Utils.java:133)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:101)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:59)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:98)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:64)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
```

Spec:
8cores, 64Gb of RAM, OS Centos7

The error reported above remains following suggestion in #80 
in VarDict script, switched from:
`DEFAULT_JVM_OPTS='"-Xms768m" "-Xmx8g"'`
to:
`DEFAULT_JVM_OPTS='"-Xms4g" "-Xmx8g"'`

right now I'm trying to re-run the cmd after the following editing of the script:
`DEFAULT_JVM_OPTS='"-Xms32g" "-Xmx60g"'`
I'll report if the command will succeed or not.

In the meantime, Is the comment by @zhongwulai in #12 still valid for the actual version of VarDict ?

----

Additionally, I'd like to report another problem (maybe it deserves another topic, I don't know)

Compiling VarDict as suggested in the README file, I faced a small problem running `./gradlew clean javadoc` due to an invalid character in one of the file. I just manually edited the file to solve the problem but that's not the point.

Once compiling finished, no `build/install/VarDict` directory was present. 
```
$ ls VarDictJava/build
# classes  distributions  docs  libs  scripts  tmp
```
running VarDict (inside scripts folder) resulted in an error due to missing files. I just edited a couple of line in the script to make it work.
`APP_HOME="'pwd -P'"` to `APP_HOME="path_to_libs_folder"`
and the line
`CLASSPATH=$APP_HOME/lib/VarDict-1.6.0.jar:$APP_HOME/lib/commons-cli-1.2.jar:$APP_HOME/lib/jregex-1.2_01.jar:$APP_HOME/lib/htsjdk-2.8.0.jar`
adjusting the part of path that points to the libraries.
By the way, I had to manually download the libraries, not sure if that was technically required or not.

**Comment by ReWeda** [comment] 2019-03-07 10:58
I figured out a way to make VarDict work properly. After a little bit of testing and debugging I properly tuned the `DEFAULT_JVM_OPTS` parameter. 
Moreover, I split regions in my .bed file into smaller overlapping chunks as suggested in #12 as suggested by @zhongwulai.

The "problem" related to the compiling phase still remains. Hope my experience in that phase could help developers.

**Comment by PolinaBevad** [comment] 2019-03-11 06:45
Davide, hello!
Sorry that you have the issue!
You are absolutely right about the way to fix OutOfMemoryError: you have to split regions in the BED file to the smaller. It is described here in Wiki: https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Error-java.lang.OutOfMemoryError:-GC-overhead-limit-exceeded  

Your next question lies in the functionality of Gradle. The option `clean` in the command will clean the whole build directory before executing the next command, i.e. `javadoc`. So the distribution will be deleted from this folder. If you want to first create the distribution and then create javadoc, you have to run: `./gradlew clean installDist` and then `./gradlew javadoc`.
Please, try to run it. Feel free to ask any questions!

**Comment by ReWeda** [comment] 2019-03-12 10:15
Thanks for your reply. I'll try what you suggested asap. Unfortunately I switch workplace a couple of times per month and right now I can't access VMs where I installed VarDict.

**Comment by PolinaBevad** [comment] 2019-04-04 14:21
Davide, hello,
I will close the issue because  I think the problem is clear and it can be fixed by that gradle command. 
If you will have any questions, please, reopen this issue!

**Closed by PolinaBevad** 2019-04-04 14:21 UTC
