### ISSUE TITLE
index out of bound error related to hard clipping still an issue

### ISSUE THREAD

**Issue by scottrk** [AstraZeneca-NGS/VarDictJava#283] opened 2020-04-02 22:53 UTC
I believe this is a similar issue as described in #253 that is still triggered in the master branch after merging of the fix mentioned in #254. The cases where this is triggered is when there is an insertion immediately next to hard clipped bases and a SNV. 

The attached example hardclipped reads will trigger the exception with the following error:

`There was Exception while processing record on AGAATTATACACCAACACATACCGCCCTGCAA on region example_genome:2-627. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: 115
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:572)
	at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:88)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
There was Exception while processing record on CGTGTGCACGGCAAGGACAGATGTCGCACATC on region example_genome:2-627. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: 99
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:572)
	at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:88)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
There was Exception while processing record on CGTCCTTAGCACATCCCAGAGCTGGGCAAGGC on region example_genome:2-627. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: 98
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:572)
	at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:88)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
There was Exception while processing record on GCACATCCCAAGGCCACCTTGCAGACATCCCC on region example_genome:2-627. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: 96
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:572)
	at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:88)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)`

Command to to run the example: 
`VarDict -N test -b test_reads.hardclipped.bam -G example_genome.fa -p -z 1 -c 1 -S 2 -E 3 -g 4 -f 0.0 -r 1 example_bed.bed`

This bug is not triggered if the command is run on the provided non-hardclipped bam file, even though they are the same reads.

[example.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/4424123/example.tar.gz)

**Comment by PolinaBevad** [comment] 2020-04-29 06:24
Hi @scottrk!
Sorry that you have the issue! Yes, I checked, and this is reproducible, but we need a little time to figure out how to fix this.
Typically we don't have the situation, when insertion starts after hard-clip in our data. Is this a real BAM or the artificial data?

**Comment by scottrk** [comment] 2020-04-29 14:44
These are real reads from a data set that I extracted and made an artificial reference from the original reference genome. I made a fix in a local fork that removes the hard clipping designation entirely during CIGAR modification prior to the other CIGAR manipulations that are performed. That "fixed the glitch", but I don't know if that's the proper solution since I'm not very familiar with the internals of VarDictJava. My thought was that hard clipping isn't really informative to variant calling since that information isn't in the read and we're not actually modifying the CIGAR in the original bam file, just how VarDictJava sees the data.

**Comment by PolinaBevad** [comment] 2020-04-29 15:33
Thank you @scottrk for reply.
At first glance I think your approach is ok, but I'll check this. Yes, you are right, we don't modify initial CIGAR.

**Comment by scottrk** [comment] 2020-04-29 20:08
Here's a patch of the changes I made. Upon reflection, I think my implementation is not fully correct. I think the removal of the hardclipping should probably be under a conditional that removes them from the CIGAR if present and then goes on with the normal CIGAR modifications. Regardless, you get the idea of what I was going for.
[Fix_hardclipping.patch.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/4554316/Fix_hardclipping.patch.txt)

**Comment by PolinaBevad** [comment] 2020-05-08 11:15
Hi @scottrk ,
I've added PR to fix this.
If we delete H bases fully there can be some artifacts, so I disabled creating of MNV\complex for this case. 
Also you have to use `-P` option when you have reads with hard clips, because mean position of variant doesn't include hard clipped bases, so variants near hard-clips will be filtered out (-P is 5 by default).
Thank you!

**Comment by scottrk** [comment] 2020-05-12 16:20
I tested your branch with the fix. It seems to have solved the issue. Will test on a few more samples and report if I run across anything else. Thanks!

**Comment by PolinaBevad** [comment] 2020-05-25 11:13
Hi @scottrk , I'll close this issue - the fix is already in master.

**Closed by PolinaBevad** 2020-05-25 11:13 UTC

**Comment by rebber** [comment] 2020-10-22 12:17
Hi,

I have a very similar error to this, which is not captured by the earlier fixes: 

```
There was Exception while processing record on KH20201014:17728542 on region 17:41264305-41264924. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: 71
        at java.lang.String.charAt(String.java:658)
        at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:523)
        at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:88)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
        at com.astrazeneca.vardict.modes.SomaticMode.processBothBamsInPipeline(SomaticMode.java:111)
        at com.astrazeneca.vardict.modes.SomaticMode.notParallel(SomaticMode.java:49)
        at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
        at com.astrazeneca.vardict.Main.main(Main.java:15)
```
and repeated for a number of reads with the same issue.

The command I run is:
```
vardict-java -G human_g1k_v37_decoy.fasta -f 0.01 -N tumor -b "indel_HC_error.tumor.bam|indel_HC_error.normal.bam" -mfreq 0.01 -nmfreq 0.01  -c 1 -S 2 -E 3 -g 4 -Q 10 problem_region.bed 
```
I have VarDictJava v 1.8.2 (installed with conda, thus the "vardict-java" call).
The error happens only when local realignment is used. With option "-k 0" it doesn't happen.
I attach a zip with minimal bams and bed which trigger the error.

I have paired reads (mapped to GRCh37) where the overlapping parts in the pairs have been trimmed with fgbio ClipBam, leaving hard clipped bases in the CIGAR. The issue happens at a very specific pattern in the CIGAR: xM3D8M3IyH (with x as num mapped and y as num hard clipped). I have tried to follow in the source code what happens to these reads, and has found the following flow for parsing the CIGAR:
- In src/main/java/com/astrazeneca/vardict/modules/CigarParser.java, CIGAR is run through function parseCigar():
    - with local realignment turned on (option -k = 1, default) the CIGAR is modified in src/main/java/com/astrazeneca/vardict/modules/CigarModifier.java with function cigarModifier.modifyCigar()
        - CIGAR of type xM3D8M3IyH matches "NOTDIG_DIG_I_DIG_M_DIG_DI_DIGI" (regex "(\\d+)D(\\d+)M(\\d+)([DI])(\\d+I)?") and is thus modified with function combineToCloseToCorrect() (line 209), which turns the 3D8M3I pattern into 11D11I, so modified CIGAR is xM11D11IyH
            - pull request #254  (fix for issue 253) makes sure to avoid CIGAR modification with similar function combineToCloseToOne() when the CIGAR starts with hard clipped bases, but no such check for this case
    - back in CigarParser.java, still within parseCigar, there is a function cleanupCigar() supposed to remove e.g. hard-clipped bases at the ends, but this operates on the original CIGAR (rec.getCigar(), rec.setCigar()), while the modified cigar in variable "cigar" is what is used going forward, so we continue with xM11D11IyH
    - in loop processCigar, 
        - the first matching element is parsed, and then (line 490) it checks if next element is a deletion, with function isCloserThenVextAndGoodBase(), 
            - this returns true, since we have deletion element after matching element (xM11D11IyH)
                - pull request #293  (fix for issue 283) makes sure to return a false from this function, if the second next element is hard clipping, but that doesn't happen for this case since there is also an insertion after the deletion, and then the hard clipping comes
        - since isCloserThenVextAndGoodBase() in line 490 gives true, it's checked if element after the deletion is an insertion with function isTwoInsertionsAhead() (line 515)
            - this returns true, since we have insertion element after deletion element (xM11D11IyH)
        - since isTwoInsertionsAhead() in line 515 returns true, the base qualities are checked up until one position after the insertion ends (line 523)
            - this fails since we have no more bases (just hard clippings), and we get the "String index out of range" error
            - it is not expected that this insertion is at end of the actual read since earlier checks should have set any insertions in the ends to soft clips, but this case wasn't discovered since there is hard clipping at the end, thus we get the error

I see multiple possible solutions:

- Avoid CIGAR modification by combineToCloseToCorrect() by checking that there isn't hard clipping following the deletion - matching - deletion/insertion - (insertion) pattern, e.g. by extending the "NOTDIG_DIG_I_DIG_M_DIG_DI_DIGI" regex to "(\\d+)D(\\d+)M(\\d+)([DI])(\\d+I)?(\\d+H)?$" and make a similar exception as for combineToCloseToOne(), but for hard clipping at the end
- Change the exception in isCloserThenVextAndGoodBase() so that false is returned whenever there is no mapping element between indel elements and any possible final hard clipping (and not only when the first deletion is immediately followed by hard clipping)
- Fix so that cleanupCigar() runs on the modified CIGAR

Is it possible that you could add a fix for this? 
I am not very experienced in writing java (just reading it), and also doesn't know how my suggested solutions would go with other parts of the logic, therefore I don't want to make a pull request with any of my solutions. But hopefully you could do this in a good way.

Many thanks!
Rebecka
[minimal_bam_github.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/5422601/minimal_bam_github.zip)
