### ISSUE TITLE
Difficulties in VarDict-1.5.4 installation

### ISSUE THREAD

**Issue by macko-tipor** [AstraZeneca-NGS/VarDictJava#124] opened 2018-07-26 06:54 UTC
Hi,

Can you, please, help me to solve VarDictJava installation problems?

I tried to upgrade VarDict-1.5.1 to VarDict-1.5.4 to take advantage of options -u and -UN.
But I came up against two different errors:
1/ "Connection timed out" exception when trying to download gradle by the gradlew script.
2/ "String index out of range: -1" exception when trying to run VarDict-1.5.3 or VarDict-1.5.4.

I give below a detailed description of what happened during my attempts of  installation.

I followed the commands included in the Readme.md document.

git clone --recursive https://github.com/AstraZeneca-NGS/VarDictJava.git
cd ~/VarDictJava
./gradlew clean installDist

The following error message was shown:

    Downloading https://services.gradle.org/distributions/gradle-4.8-bin.zip
    Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

I got the same message when trying:
./gradlew distZip

Then I installed gradle-4.9 manually, added the gradle-4.9/bin folder to the PATH and repeated the ./gradlew clean installDist command.
The same error message was shown again.

Therefore, I tried a different way.
I downloaded VarDict-1.5.4.zip, created an install folder in VarDictJava folder, and unzipped VarDict-1.5.4.zip there. The bin and lib folders were created.
I have successfully used VarDict-1.5.1 in the same way so far.
However, when I tried to use VarDict-1.5.4, the following error message came:

    java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.astrazeneca.vardict.VarDict.somaticParallel(VarDict.java:394)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:301)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:80)
        at com.astrazeneca.vardict.Main.run(Main.java:159)
        at com.astrazeneca.vardict.Main.main(Main.java:31)
    Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.charAt(String.java:658)
        at com.astrazeneca.vardict.VarDict.isHasAndNotEquals(VarDict.java:4422)
        at com.astrazeneca.vardict.VarDict.modifyCigar(VarDict.java:6825)
        at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1673)
        at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2917)
        at com.astrazeneca.vardict.VarDict$ToVarsWorker.call(VarDict.java:5753)
        at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5774)
        at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5758)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

The following command led to the above exception:

    "$VARDICT" \
        -th 48 \
        -G "$Refseq" \
        -f 0.10 \
        -r 8 \
        -3 \
        -b ""$INPUT_TUMOR"|"$INPUT_NORMAL"" \
        -N "$SAMPLE_TUMOR" \
        -c 1 \
        -S 2 \
        -E 3 \
        "$TARGET_INTERVALS_VARDICT" | "$DIR_VARDICT"/testsomatic.R |   "$DIR_VARDICT"/var2vcf_paired.pl \
            -f 0.10 \
            -r 8 \
            -N ""$SAMPLE_TUMOR"|"$SAMPLE_NORMAL"" \
            > "$OUTPUT"

I repeated the installation steps with VarDict-1.5.3 and VarDict-1.5.2.
I got the same error message when trying to run VarDict-1.5.3.
On the contrary, VarDict-1.5.2 works well.

Now I can apply VarDict-1.5.2 which includes the -u and -UN options.
But what can I do to install the latest version?
What can be the problem? May our system settings have something incompatible with the latest two versions?
I would like to follow the new VarDict versions in the future and I am afraid of getting the same error message with each one if this problem remains unsolved.

My java version is 1.8.0_171.

Thank you very much for your help in advance!

**Comment by mjafin** [comment] 2018-07-26 07:17
@PolinaBevad could your team provide some input here?
@macko-tipor it may be helpful if you provide a set of bed and bam files for testing where VarDict fails

**Comment by PolinaBevad** [comment] 2018-07-26 07:20
@macko-tipor , hello!
Sorry for these errors.
The first error with "Connection timed out" is strange behavior: it can appear if you have no access to the gradle.org website because of the firewall, proxy or network problems. Can you ping this site from the system where you try to build project?  
Anyway, if you manually installed gradle, you can start it, not with `./gradlew clean install` (it will start gradle wrapper and try to download the version from the site), but with `gradle clean installDist`. Please, try it to build the project. You can check what version is installed manually on your system with `gradle -v` command.
The second error leads to updates in Vardict 1.5.3: there were big changes in local realignment, especially in modifying Cigar process. This error isn't reproduced on our test data in the paired mode with these options. Could you please upload the small parts of bam files and bed (or region)?

**Comment by macko-tipor** [comment] 2018-07-26 08:59
Hi @PolinaBevad and @mjafin ,


Thank you for the quick answer.

I checked the gradle version installed on my server, it is Gradle 4.9 .
I used "gradle clean installDist" command to build the project. The following message came:

    Starting a Gradle Daemon (subsequent builds will be faster)
    > Task :compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not resolve all files for configuration ':compileClasspath'.
    > Could not resolve commons-cli:commons-cli:1.2.
      Required by:
          project :
       > Could not resolve commons-cli:commons-cli:1.2.
          > Could not get resource 'https://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom'.
             > Could not GET 'https://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom'.
                > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.112.215] failed: connect timed out
    > Could not resolve com.edropple.jregex:jregex:1.2_01.
      Required by:
          project :
       > Could not resolve com.edropple.jregex:jregex:1.2_01.
          > Could not get resource 'https://repo.maven.apache.org/maven2/com/edropple/jregex/jregex/1.2_01/jregex-1.2_01.pom'.
            n > Could not GET 'https://repo.maven.apache.org/maven2/com/edropple/jregex/jregex/1.2_01/jregex-1.2_01.pom'.
                > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.112.215] failed: connect timed out
    > Could not resolve com.github.samtools:htsjdk:2.8.0.
      Required by:
          project :
       > Could not resolve com.github.samtools:htsjdk:2.8.0.
          > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/samtools/htsjdk/2.8.0/htsjdk-2.8.0.pom'.
             > Could not GET 'https://repo.maven.apache.org/maven2/com/github/samtools/htsjdk/2.8.0/htsjdk-2.8.0.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.112.215] failed: connect timed out

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 37s
    2 actionable tasks: 1 executed, 1 up-to-date

I suspected that this problem might arise from the fact that the remote server I use for the evaluations has no internet connection.
Therefore I repeated the above command on the PC from which I have control over the remote server. All softwares are installed on it, too.
Unfortunately, I got a similar error message.

I uploaded chr1 part of the bed file I use. It is for refseq human_g1k_v37.fasta.

[targets.bed.b37.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/2231139/targets.bed.b37.txt)

Are the chr1 parts of bam and bed files sufficient for you?
If yes, I will try to create and upload bam slices for chr1, too.

**Comment by PolinaBevad** [comment] 2018-07-26 09:46
@macko-tipor , the errors show that there are problems with Internet connection. I think that the second PC also can have some problems with it. To check this make `ping gradle.org -c 5` and try to manually download any file, that are pointed in error. For example I check one of them:   `https://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom` , it opens in browser and shows simple XML file. Sometimes system administrator forbids downloading of some files, so maybe you can ask for his help.

The bed file is OK, but yes, we need bam file to reproduce the error, please upload it.

**Comment by macko-tipor** [comment] 2018-07-26 10:01
I created the chr1 region of a tumor-normal pair. I tried to upload them, but neither BAM nor CRAM file type seems to be supported. Should I try to zip them? Or in what form should I upload them?

**Comment by PolinaBevad** [comment] 2018-07-26 10:10
@macko-tipor , yes it is OK to make zip or tar archive with BAM. If it will be too large to upload here, you can upload to any file sharing service and provide a link to it.

**Comment by macko-tipor** [comment] 2018-07-26 11:02
The BAMs can be downloaded from the following links:

https://drive.google.com/open?id=17553EpvDY3iMhx1KC5MHh42MSVNEEzgR
https://drive.google.com/open?id=1xODrwlZm7n8wzSkTjAK8jNwzFT1cCkID

I checked them. The records of the downloaded files can be seen by "samtools view" command.

I hope they will work for you, too.

**Comment by PolinaBevad** [comment] 2018-07-30 11:58
@macko-tipor , the bam files are readable, thank you!

We reproduced the error on these bams and found where exactly it appears: it is the new part of the algorithm for modifying CIGAR on mis-softly clipped reads. 
We will fix it in one of the following versions. When the PR will be ready, I will link it to this issue, so you will know about the change.

For now, you can use VarDictJava 1.5.2 or, if this is suitable for your pipeline, temporarily disable local realignment in VarDictJava 1.5.4 by including `-k 0` option. This option disables the whole modify cigar and realignment features, so the sensitivity of VarDict will decrease, but you can test it on your environment to decide whether the results are right for you.

**Comment by macko-tipor** [comment] 2018-07-30 14:10
Thank you very much for helping me in this issue.

I will try both ways you suggested and compare the results.
Anyway, I think, using VarDictJava 1.5.2 is suitable for my pipeline.

Best regards!

**Comment by PolinaBevad** [comment] 2018-09-18 12:54
@macko-tipor, hello!
We fix the error with `StringOutOfBoundException`. There is no release for now (we will create it soon), but the fix is already merged in the `master` branch, so you can pull the changes from `master` and re-build VarDictJava with `./gradlew clean installDist` command. It has to be done from the computer with Internet connection.
Or you can wait for VarDictJava 1.5.5 release where this fix will be included.

**Comment by PolinaBevad** [comment] 2018-09-27 07:07
@macko-tipor , thank you for the answer and reporting this issue! We also created release 1.5.5: https://github.com/AstraZeneca-NGS/VarDictJava/releases/tag/1.5.5
I will close the issue. If the problem appears, please, re-open it.

**Closed by PolinaBevad** 2018-09-27 07:07 UTC
