### ISSUE TITLE
Error: A valid CRAM reference was not supplied

### ISSUE THREAD

**Issue by gevro** [AstraZeneca-NGS/VarDictJava#249] opened 2019-08-10 21:06 UTC
Hi,
I'm getting the following error in VarDict:

Exception in thread "main" java.lang.IllegalStateException: A valid CRAM reference was not supplied and one cannot be acquired via the property settings reference_fasta or use_cram_ref_download

But I am definitely specifying a valid Fasta file with the -G setting.

What is the issue?

**Comment by PolinaBevad** [comment] 2019-08-12 07:31
Hi, @gevro,

We officially don't support CRAM files, because they have some particular qualities in working with important for variant calling NM and MD tags: these tags may be absent in CRAM file and this behavior depends on the writer that was used for creating CRAM. BAM file always contains these tags. 

This specific error relates to htsjdk library, and in most cases it means that reference file is absent in the place that was pointed while creating CRAM file. Because we don't use CRAM features of htsjdk, you have to determine reference path in defaults so htsjdk can use it.

So I recommend that you convert CRAM to BAM file because some NM calculations can be made wrong, but if you want to use CRAM file, you have use property for htsjdk:
`-Dsamjdk.reference_fasta=path/to/fasta`
Add it to build.gradle here: https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/build.gradle#L20 and build it. Another way (without re-building) is to add this to variable `DEFAULT_JVM_OPTS` in the file `build\install\Vardict\bin\VarDict` that runs VarDict.

**Comment by gevro** [comment] 2019-08-12 21:50
No problem, I will just convert to BAM. Thank you.

**Comment by PolinaBevad** [comment] 2019-08-14 06:57
@gevro , ok, I will close this one.

**Closed by PolinaBevad** 2019-08-14 06:57 UTC

**Comment by GSBaohuaGu** [comment] 2023-02-24 06:37
> @gevro , ok, I will close this one.



> Hi, @gevro,
> 
> We officially don't support CRAM files, because they have some particular qualities in working with important for variant calling NM and MD tags: these tags may be absent in CRAM file and this behavior depends on the writer that was used for creating CRAM. BAM file always contains these tags.
> 
> This specific error relates to htsjdk library, and in most cases it means that reference file is absent in the place that was pointed while creating CRAM file. Because we don't use CRAM features of htsjdk, you have to determine reference path in defaults so htsjdk can use it.
> 
> So I recommend that you convert CRAM to BAM file because some NM calculations can be made wrong, but if you want to use CRAM file, you have to use property for htsjdk: `-Dsamjdk.reference_fasta=path/to/fasta` Add it to build.gradle here: https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/build.gradle#L20 and build it. Another way (without re-building) is to add this to variable `DEFAULT_JVM_OPTS` in the file `build/install/Vardict/bin/VarDict` that runs VarDict.

II tried the method above to solve the problem that the input is in cram format, but still reported an error。
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/bzip2/BZip2CompressorOutputStream
	at htsjdk.samtools.cram.structure.block.Block.getUncompressedContent(Block.java:203)
	at htsjdk.samtools.cram.build.CramIO.readSAMFileHeader(CramIO.java:316)
	at htsjdk.samtools.cram.build.CramIO.readCramHeader(CramIO.java:225)
	at htsjdk.samtools.cram.build.CramContainerIterator.<init>(CramContainerIterator.java:22)
	at htsjdk.samtools.CRAMIterator.<init>(CRAMIterator.java:86)
	at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:226)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:219)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:422)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:208)
	at com.astrazeneca.vardict.VarDictLauncher.readChr(VarDictLauncher.java:187)
	at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:80)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:49)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more
