### ISSUE TITLE
VarDict throws stringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by haseley** [AstraZeneca-NGS/VarDictJava#38] opened 2016-05-06 22:40 UTC
Hello,

   Sometimes when encountering severely clipped reads VarDict will throw an index out of bounds exception and exit:Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.charAt(String.java:646)
    at com.astrazeneca.vardict.VarDict.isHasAndNotEquals(VarDict.java:4084)
    at com.astrazeneca.vardict.VarDict.modifyCigar(VarDict.java:6238)
    at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1548)
    at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2554)
    at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:301)
    at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:254)
    at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
    at com.astrazeneca.vardict.Main.run(Main.java:134)
    at com.astrazeneca.vardict.Main.main(Main.java:25)

I've attached an example of a problematic alignment (aligned to hg38).  I realize this read likely should not be aligning here, but we do occassionally get output like this from our aligner.  Since it is a valid bam entry it would be nice if VarDict could handle this so we don't have to filter these out manually since this can be expensive on large bam files.  Thanks!

Command: VarDict -G ./hg38.fa -b indexOutOfBoundsError.bam -N "problem" -c 1 -S 2 -E 3 -g 4 myVeryShortBed.bed
[indexOutOfBoundsError.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/253137/indexOutOfBoundsError.zip)

**Comment by mjafin** [comment] 2016-05-09 06:51
@zhongwulai and @jabbarish could you look at addressing this problem both in Perl and Java?

**Comment by jabbarish** [comment] 2016-05-09 11:31
@mjafin sure.

**Comment by rhshah** [comment] 2016-05-13 19:01
Hello  I am having similar issue, 
I assumed these were fixed in 1.45 but looks like not:

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -151
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
	at java.util.concurrent.FutureTask.get(FutureTask.java:111)
	at com.astrazeneca.vardict.VarDict.somaticParallel(VarDict.java:338)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:251)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
Caused by: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -151
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
	at java.util.concurrent.FutureTask.get(FutureTask.java:111)
	at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5356)
	at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5339)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -151
	at java.lang.String.substring(String.java:1875)
	at com.astrazeneca.vardict.Utils.substr(Utils.java:80)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2904)
	at com.astrazeneca.vardict.VarDict$ToVarsWorker.call(VarDict.java:5334)
	at com.astrazeneca.vardict.VarDict$ToVarsWorker.call(VarDict.java:5308)
	... 5 more

Attached is the problematic site. Would appreciate any insights. 
We are actually seeing similar issues in more samples. Again our BAM files are re-aligned by ABRA.

[pten.bam.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/263908/pten.bam.zip)

**Comment by jabbarish** [comment] 2016-05-13 19:43
Java throws an exception in case of the index of an array is less than zero, however Perl doesn't throw anything in such case. 
Here is the fresh request by Tim Fennel https://github.com/AstraZeneca-NGS/VarDictJava/pull/40 suggesting an attempt to fix the issue 38.
Let's wait for the comments from @zhongwulai

**Comment by rhshah** [comment] 2016-05-13 20:54
Actually because of your reply I ran it on the Perl Version and it actually fails at the same place giving multiple errors, I am just putting here the uniq list:

substr outside of string at vardict line 1467.
Use of uninitialized value in join or string at vardict line 1466.
Use of uninitialized value in join or string at vardict line 2365.
Use of uninitialized value in join or string at vardict line 2367.
Use of uninitialized value in string ne at vardict line 2582.
Use of uninitialized value in string ne at vardict line 2585.

Sorry I should not have put the issue here for the perl version. 

Thanks in advance.

**Comment by rhshah** [comment] 2016-05-23 16:31
Thank you for working on this, but v1.4.6 still fails on the same region that I provided above. Will really appreciate your help.

**Comment by mjafin** [comment] 2016-05-23 20:43
Bummer. @jabbarish would you be able to take a look? Probably a matter of unorthodox cigar strings caused by the explicit realigner

**Comment by jabbarish** [comment] 2016-05-24 21:00
@rhshah @mjafin 
We think the code fails due to cigar string with big deletions like this: 1M899D96M.  There are very many such cigar strings in the provided bam file. VarDictJava throws exceptions because the reference for variant calling in this particular case  is smaller than the read  length counting the deletion. By default the reference for a region taken is +700 length.  There is a parameter -x, which sets the number of nucleotides to extend. Use it and the VarDict will succeed with the bam.

**Comment by rhshah** [comment] 2016-05-24 22:29
@jabbarish thank you indeed it succeeded and it does make sense As ABRA can realign deletions upto 2000bp will probably set it to that.

**Closed** 2017-02-15 15:51 UTC
