### ISSUE TITLE
Some high frequency SNVs are not called

### ISSUE THREAD

**Issue by smzt** [AstraZeneca-NGS/VarDictJava#109] opened 2018-06-14 06:53 UTC
Dear developers,
I'm running VarDict with some control samples from Horizon. These reference DNAs have known variants that have been genotyped with other non-NGS techniques so their frequency is known. From the list of variant they provide, variant frequencies vary from 1 up to 93% for one of the reference samples. 

I'm unable to see these 6 variants in my results from a total of 37 variants that are present in the regions of interes:
chr12   25209843        COSM3753105     A       G       .       PASS    GENE=KRAS;VARIANT=p.D173D;VF=0.27;Variant_type=SNP;SF=0
chr15   66435113        COSM1235481     A       C       .       PASS    GENE=MAP2K1;VARIANT=p.Q56P;VF=0.26;Variant_type=SNP;SF=0
chr17   7676154 COSM250061      G       C       .       PASS    GENE=TP53;VARIANT=p.P72R;VF=0.93;Variant_type=SNP;SF=0
chr3    179234297       COSM775 A       G       .       PASS    GENE=PIK3CA;VARIANT=p.H1047R;VF=0.17;Variant_type=SNP;SF=0
chr5    112827157       COSM1432175     T       C       .       PASS    GENE=APC;VARIANT=p.Y486Y;VF=0.26;Variant_type=SNP;SF=0
chr5    112840862       rs866006        T       G       .       PASS    GENE=APC;VARIANT=p.S1756;VF=0.32;Variant_type=SNP;SF=0

I'm running VarDict with the following parameters 
./VarDictJava/build/install/VarDict/bin/VarDict -z 1 -c 1 -S 2 -E 3 -g 4 -f 0 -F 0x700 -q 30 -th 10  -G Homo_sapiens.GRCh38_chr.fa  -N HD827x1-2-149 -b ../HD827x1-2-149_forVarCall.bam -c 1 -S 2 -E 3 capture.merge.bed | teststrandbias.R | ./VarDictJava/VarDict/var2vcf_valid.pl -N HD827x08-1-149 -E -A -f 0 > HD827x1-2-149.vcf

The variant in position chr17:7676154G>C has a known frequency of 0.93. I checked it in IGV and I can perfectly see the variant (see image below). No strand bias. Good quality reads. Correct insert size. More than enough coverage.
![captura de pantalla de 2018-06-13 18-43-07](https://user-images.githubusercontent.com/32428329/41395179-0c6b67e2-6fad-11e8-8b98-0513b519a530.png)

VarDict reports this variant at that position:
chr17	7676154	.	G	T	32	f0.02	SAMPLE=HD827x1-2-149;TYPE=SNV;DP=333;VD=2;AF=0.006;BIAS=2:0;REFBIAS=5:5;VARBIAS=0:2;PMEAN=39;PSTD=1;QUAL=32.5;QSTD=1;SBF=0.4697;ODDRATIO=0;MQ=60;SN=4;HIAF=1.0000;ADJAF=0;SHIFT3=2;MSI=6;MSILEN=1;NM=1.5;HICNT=2;HICOV=2;LSEQ=CTGCTGGTGCAGGGGCCACG;RSEQ=GGGGAGCAGCCTCTGGCATT	GT:DP:VD:AD:AF:RD:ALD	0/0:333:2:10,2:0.006:5,5:0,2

In the intermediate .txt file, for this position, it shown this information:
HD827x1-2-149	chr17	chr17	7676154	7676154	G	T	333	2	5	5	0	2	G/T	0.0060	2;0	39.0	1	32.5	1	60.0	4.000	1.0000	0	2	6.000	1	1.5	2	2	CTGCTGGTGCAGGGGCCACG	GGGGAGCAGCCTCTGGCATT	chr17:7675941-7676420	SNV

This variant is G>T but the reported variant is a G>C change. Vardict seems to be focusing on the allele that is seen with the lowest frequency. I've seen other threads where multiallelic variant are misscalled. I remove the realignment step with -k 0, use the -A flag with no success. I do not know if there is any other parameter I can tweak that would help me finding these variants.

Any help would be much appreciated.

Best regards,

Sheila

**Comment by pcingola** [comment] 2018-07-20 13:10
Hi. Would it be possible for you to share that slice of tour BAM files so we can reproduce and debug the error? Thank you.

**Comment by PolinaBevad** [comment] 2018-09-11 16:13
@smzt, hello!
Does this error still appear? We are waiting for the BAM file to reproduce it. Or you can provide a link where you download it because we can't find it on the internet by name (HD827x1-2-149_forVarCall.bam).

**Comment by PolinaBevad** [comment] 2018-10-29 14:59
@smzt, hello!
Sorry, we will close the issue because there was no answer from you about BAM file.
You can re-open it if needed. Also, there were few releases of VarDictJava since you created the issue, so maybe this error was gone. 
Thank you!

**Closed by PolinaBevad** 2018-10-29 14:59 UTC
