### ISSUE TITLE
VarDictJava doesn't call variants near end of chromosome

### ISSUE THREAD

**Issue by gpratt** [AstraZeneca-NGS/VarDictJava#235] opened 2019-06-17 23:10 UTC
Hello,

I think I've discovered a bug that only occurs near the ends of reference sequences as was found in a full mitochondrial variant calling pipeline.

It appears that the last ~20 or so sites within a reference sequence produce invalid output from VarDictJava.

To show this effect, I've included a small toy dataset that contains a short artificial reference sequence and a BAM file with a single read that has a few single nucleotide mismatches. The mismatches should be located at positions 32 and 50 in the reference sequence.

**Data Set**: [reproducing_data.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/3299164/reproducing_data.tar.gz)

Contents:

```bash
❯ tree reproducing_data
reproducing_data
├── test.bed
├── test.fa
├── test.fa.fai
├── test_alt_alleles.bam
└── test_alt_alleles.bam.bai
```

When VarDictJava is run with the toy dataset:

```
VarDictJava/build/install/VarDict/bin/VarDict \
    -N test \
    -b test_alt_alleles.bam \
    -G test.fa \
    -p \
    -z 1 \
    -c 1 \
    -S 2 \
    -E 3 \
    -g 4 \
    -f 0.0 \
    -r 1 test.bed
```

The output is:

```txt
test	test	chrT	32	32	T	G	1	1	0	0	0	1	G/G	1.0000	0;0	4.0	0	90.0	0	30.0	2.000	1.0000	0	2	8.000	4	0	1	1	TACGTACGTACGTACGTACG	ACG	chrT:1-52	SNV	0	0
test	test	chrT	33	33	A	A	1	0	0	1	0	0	A/A	0	0;0	5.0	0	90.0	0	30.0	2.000	1.0000	0	0	0	0	0	1	1	0	0	chrT:1-52		0	0
test	test	chrT	34	34	C	C	1	0	0	1	0	0	C/C	0	0;0	6.0	0	90.0	0	30.0	2.000	1.0000	0	0	0	0	0	1	1	0	0	chrT:1-52		0	0
test	test	chrT	35	35	G	G	1	0	0	1	0	0	G/G	0	0;0	7.0	0	90.0	0	30.0	2.000	1.0000	0	0	0	0	0	1	1	0	0	chrT:1-52		0	0
test	test	chrT	36	36		T	1	1	0	0	0	1	T/T	1.0000	0;0	8.0	0	90.0	0	30.0	2.000	1.0000	0	0	7.000	4	0	1	1	TACGTACGTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	37	37		A	1	1	0	0	0	1	A/A	1.0000	0;0	9.0	0	90.0	0	30.0	2.000	1.0000	0	0	7.000	4	0	1	1	ACGTACGTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	38	38		C	1	1	0	0	0	1	C/C	1.0000	0;0	10.0	0	90.0	0	30.0	2.000	1.0000	0	0	7.000	4	0	1	1	CGTACGTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	39	39		G	1	1	0	0	0	1	G/G	1.0000	0;0	11.0	0	90.0	0	30.0	2.000	1.0000	0	0	6.000	4	0	1	1	GTACGTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	40	40		T	1	1	0	0	0	1	T/T	1.0000	0;0	12.0	0	90.0	0	30.0	2.000	1.0000	0	0	6.000	4	0	1	1	TACGTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	41	41		A	1	1	0	0	0	1	A/A	1.0000	0;0	12.0	0	90.0	0	30.0	2.000	1.0000	0	0	6.000	4	0	1	1	ACGTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	42	42		C	1	1	0	0	0	1	C/C	1.0000	0;0	11.0	0	90.0	0	30.0	2.000	1.0000	0	0	6.000	4	0	1	1	CGTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	43	43		G	1	1	0	0	0	1	G/G	1.0000	0;0	10.0	0	90.0	0	30.0	2.000	1.0000	0	0	5.000	4	0	1	1	GTACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	44	44		T	1	1	0	0	0	1	T/T	1.0000	0;0	9.0	0	90.0	0	30.0	2.000	1.0000	0	0	5.000	4	0	1	1	TACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	45	45		A	1	1	0	0	0	1	A/A	1.0000	0;0	8.0	0	90.0	0	30.0	2.000	1.0000	0	0	5.000	4	0	1	1	ACGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	46	46		C	1	1	0	0	0	1	C/C	1.0000	0;0	7.0	0	90.0	0	30.0	2.000	1.0000	0	0	5.000	4	0	1	1	CGTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	47	47		G	1	1	0	0	0	1	G/G	1.0000	0;0	6.0	0	90.0	0	30.0	2.000	1.0000	0	0	4.000	4	0	1	1	GTACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	48	48		T	1	1	0	0	0	1	T/T	1.0000	0;0	5.0	0	90.0	0	30.0	2.000	1.0000	0	0	4.000	4	0	1	1	TACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	49	49		G	1	1	0	0	0	1	G/G	1.0000	0;0	4.0	0	90.0	0	30.0	2.000	1.0000	0	0	4.000	4	0	1	1	ACGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	50	50		C	1	1	0	0	0	1	C/C	1.0000	0;0	3.0	0	90.0	0	30.0	2.000	1.0000	0	0	4.000	4	0	1	1	CGTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	51	51		G	1	1	0	0	0	1	G/G	1.0000	0;0	2.0	0	90.0	0	30.0	2.000	1.0000	0	0	3.000	4	0	1	1	GTACG	0	chrT:1-52	Complex	0	0
test	test	chrT	52	52		T	1	1	0	0	0	1	T/T	1.0000	0;0	1.0	0	90.0	0	30.0	2.000	1.0000	0	0	3.000	4	0	1	1	TACG	0	chrT:1-52	Complex	0	0
test	test	chrT	29	29	A	A	1	0	0	1	0	0	A/A	0	0;0	1.0	0	90.0	0	30.0	2.000	1.0000	0	0	0	0	0	1	1	0	0	chrT:1-52		0	0
test	test	chrT	30	30	C	C	1	0	0	1	0	0	C/C	0	0;0	2.0	0	90.0	0	30.0	2.000	1.0000	0	0	0	0	0	1	1	0	0	chrT:1-52		0	0
test	test	chrT	31	31	G	G	1	0	0	1	0	0	G/G	0	0;0	3.0	0	90.0	0	30.0	2.000	1.0000	0	0	0	0	0	1	1	0	0	chrT:1-52		0	0

```

The SNV at site 32 is detected, however the SNV at site 50 is not.

Additionally, at sites 36-52 there are no `REF` alleles listed and each base is tagged as a `Complex` variant.

In addition to not calling variants correctly at this region in all reference sequences (near the end), the output will generate an invalid VCF file.

Thanks again for any thoughts or help!

**Comment by PolinaBevad** [comment] 2019-06-18 12:47
Gabriel, hello!

I reproduced the bug and found the cause. Yes, it appears at the end of the chromosome and we don't have to decrease site by 17 bp for searching of the chimeric reads as usual. 

It is fixed in PR #235 by checking the current site: we will use the full length of the sequence at the end of the chromosome. The refalleles and types of the variants are now also correct. I also found that there were sometimes incorrect total coverages at the end of the chromosome, and now they are calculated correctly.

It will be great if you can try the branch from PR to check if it is ok now on your dataset.

Thank you for preparing the test case! I added it to our integration test case set.

**Comment by gpratt** [comment] 2019-06-18 18:09
I've tested it and it works perfectly!

Thanks so much for the quick fix.

**Comment by PolinaBevad** [comment] 2019-07-17 06:50
Gabriel, hello!

I will close this issue: PR with the fix was merged in master branch. 
Thank you for finding this edge case problem!

**Closed by PolinaBevad** 2019-07-17 06:50 UTC

**Comment by gpratt** [comment] 2019-07-17 14:14
Thank you!
