### ISSUE TITLE
DP: Total Depth VD: Variant depth AF: Allele frequency fields question

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#242] opened 2019-07-10 18:03 UTC
Hi,
Here are the DP, VD and AF field from one of my samples

DP=1134;VD=65;AF=2.0968

Given the definitions of these fields I would expect AF= VD / DP 

If I do this calculation I get 65 / 1134 = 0.0573 -> or if AF is given in % then 5.7%

But AF is calculated as 2.09 in my VCF file

Can you please explain it to me the calculation for AF ? 

Here is a link to my VCF file: https://drive.google.com/open?id=17xQHOXSblK0HxfB7yU7LC4ITFqHLpgYP

The above field can be extracted using 

`less T7-75.mergedChrs.vcf.gz |grep -P "10\t11291573"`

**Comment by PolinaBevad** [comment] 2019-07-11 06:52
Hamdi, hello!
Yes, AF must be calculated as you mention. But I think that DP wasn't correctly printed for this variant: we found several cases where AF was > 1, but it wasn't fixed yet. Is it possible that you send me the part of BAM file with this DEL to check the problem? I guess region chr10:11290000-11297000 will be enough.

**Comment by thkitapci** [comment] 2019-07-11 15:06
Hi,
I included a link to the full bam file in my post. Can you access it ? If
you can’t please let me know and I will try to send it again.

Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment] 2019-07-11 15:17
Hi Hamdi,
I see the link to VCF file, but no link to BAM file. To find out where is the problem BAM file would be preferable because VCF contains only the final information about variants and no data about reads.
Full BAM isn't required, you can upload only the part that I mentioned.

**Comment by thkitapci** [comment] 2019-07-12 16:51
Hi @PolinaBevad,
Here is a link to the bam file https://de.cyverse.org/dl/d/4D7A296B-BD73-4B52-8AF7-C8BEE2EF2CAA/T7-75_S10_R1_001_u_1.bam 

Please let me know what is the issue here.

**Comment by thkitapci** [comment] 2019-07-12 19:07
@PolinaBevad ,
There is another observation that I just realized. If you look at the VCF file to the locations right after the 3640 bp DEL at Chr 10 position 11291573 there are many SNPs such as at positions 

11291574
11291584
11291615

How can there be a deletion of 3640 bp starting at position 11291573 and SNPs within this "DEL" region ? 

Thanks
Hamdi

**Comment by PolinaBevad** [comment] 2019-07-15 08:50
Hamdi, hello!
Thank you for providing BAM and VCF files and also link to genome browser!
I am downloading BAM now (it is quite slow...), and I will try to figure out what the problem is.  Perhaps the DEL, in this case, was incorrectly defined. I will come back to you when I find the answers.

**Comment by thkitapci** [comment] 2019-07-15 21:31
Hi @PolinaBevad,
Thanks for your help. There is another position that is detected as a DUP in 5 of the samples as shown below. Based on the genome browser track I am worried this position might have a problem as well

Here is the genome browser track https://genome.ucsc.edu/s/thkitapci/Mouse_T7_11_84179922_84195682_VCF_BAM

Here are the lines corresponding to this position from the genome browser

VCF lines shown below appear in the same order in the genome browser track

This one is detected as a DUP of 15760 bp 

11      84179922        .       C       .       0       f0.01   SAMPLE=T7-1_chr11;TYPE=;DP=46;VD=0;AF=0;BIAS=2:0;REFBIAS=29:17;VARBIAS=0:0;PMEAN=48.2;PSTD=1;QUAL=39.3;QSTD=1;SBF=1;ODDRATIO=0;MQ=255;SN=45;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0.3;HICNT=45;HICOV=45;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=0        GT:DP:VD:AD:AF:RD:ALD   0/0:46:0:46:0:29,17:0,0

11      84179922        .       C       .       0       f0.01   SAMPLE=T7-2_chr11;TYPE=;DP=38;VD=0;AF=0;BIAS=2:0;REFBIAS=31:7;VARBIAS=0:0;PMEAN=43.6;PSTD=1;QUAL=38.1;QSTD=1;SBF=1;ODDRATIO=0;MQ=255;SN=11.667;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0.3;HICNT=35;HICOV=35;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=0     GT:DP:VD:AD:AF:RD:ALD   0/0:38:0:38:0:31,7:0,0

11      84179922        .       C       .       0       f0.01   SAMPLE=T7-3_chr11;TYPE=;DP=35;VD=0;AF=0;BIAS=2:0;REFBIAS=22:13;VARBIAS=0:0;PMEAN=39;PSTD=1;QUAL=37.1;QSTD=1;SBF=1;ODDRATIO=0;MQ=255;SN=7.75;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0.6;HICNT=31;HICOV=31;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=0        GT:DP:VD:AD:AF:RD:ALD   0/0:35:0:35:0:22,13:0,0

11      84179922        .       C       .       0       f0.01   SAMPLE=T7-4_chr11;TYPE=;DP=60;VD=0;AF=0;BIAS=2:0;REFBIAS=36:24;VARBIAS=0:0;PMEAN=42.5;PSTD=1;QUAL=39.1;QSTD=1;SBF=1;ODDRATIO=0;MQ=255;SN=29;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0.3;HICNT=58;HICOV=58;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=0        GT:DP:VD:AD:AF:RD:ALD   0/0:60:0:60:0:36,24:0,0

11      84179922        .       C       .       0       f0.01   SAMPLE=T7-287_chr11;TYPE=;DP=58;VD=0;AF=0;BIAS=2:0;REFBIAS=40:18;VARBIAS=0:0;PMEAN=50.6;PSTD=1;QUAL=39.3;QSTD=1;SBF=1;ODDRATIO=0;MQ=255;SN=28;HIAF=1.0000;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0.1;HICNT=56;HICOV=56;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=0      GT:DP:VD:AD:AF:RD:ALD   0/0:58:0:58:0:40,18:0,0

11      84179922        .       C       <DUP>   80      PASS    SAMPLE=T7-66_chr11;TYPE=DUP;DP=97;VD=4;AF=0.0412;BIAS=2:2;REFBIAS=32:21;VARBIAS=2:2;PMEAN=23;PSTD=1;QUAL=40.4;QSTD=1;SBF=1;ODDRATIO=1.51225;MQ=255;SN=8;HIAF=0.0741;ADJAF=0.0412;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=4;HICOV=54;LSEQ=GGTCCCTGCGTGCCGCCAGC;RSEQ=ATGAGGTGAGAAGAATTGCT;DUPRATE=0;SVTYPE=DUP;SVLEN=15760;SPLITREAD=4;SPANPAIR=0     GT:DP:VD:AD:AF:RD:ALD   0/1:97:4:53,4:0.0412:32,21:2,2

11      84179922        .       C       <DUP>   74      PASS    SAMPLE=T7-67_chr11;TYPE=DUP;DP=101;VD=4;AF=0.0396;BIAS=2:2;REFBIAS=26:15;VARBIAS=3:1;PMEAN=24.5;PSTD=1;QUAL=37.4;QSTD=1;SBF=1;ODDRATIO=1.71139101861993;MQ=255;SN=8;HIAF=0.0976;ADJAF=0.0396;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=4;HICOV=41;LSEQ=GGTCCCTGCGTGCCGCCAGC;RSEQ=ATGAGGTGAGAAGAATTGCT;DUPRATE=0;SVTYPE=DUP;SVLEN=15760;SPLITREAD=4;SPANPAIR=0 GT:DP:VD:AD:AF:RD:ALD   0/1:101:4:41,4:0.0396:26,15:3,1

11      84179922        .       C       <DUP>   63      PASS    SAMPLE=T7-68_chr11;TYPE=DUP;DP=119;VD=3;AF=0.0252;BIAS=2:2;REFBIAS=32:12;VARBIAS=2:1;PMEAN=19;PSTD=1;QUAL=39.9;QSTD=1;SBF=1;ODDRATIO=1.32476;MQ=255;SN=6;HIAF=0.0652;ADJAF=0.0252;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=3;HICOV=46;LSEQ=GGTCCCTGCGTGCCGCCAGC;RSEQ=ATGAGGTGAGAAGAATTGCT;DUPRATE=0;SVTYPE=DUP;SVLEN=15760;SPLITREAD=3;SPANPAIR=0    GT:DP:VD:AD:AF:RD:ALD   0/1:119:3:44,3:0.0252:32,12:2,1

11      84179922        .       C       <DUP>   77      PASS    SAMPLE=T7-69_chr11;TYPE=DUP;DP=153;VD=4;AF=0.0261;BIAS=2:2;REFBIAS=56:19;VARBIAS=3:1;PMEAN=24.8;PSTD=1;QUAL=38.9;QSTD=1;SBF=1;ODDRATIO=1.01763562538797;MQ=255;SN=8;HIAF=0.0519;ADJAF=0.0261;SHIFT3=0;MSI=0;MSILEN=0;NM=0.8;HICNT=4;HICOV=77;LSEQ=GGTCCCTGCGTGCCGCCAGC;RSEQ=ATGAGGTGAGAAGAATTGCT;DUPRATE=0;SVTYPE=DUP;SVLEN=15760;SPLITREAD=4;SPANPAIR=0       GT:DP:VD:AD:AF:RD:ALD   0/1:153:4:75,4:0.0261:56,19:3,1

11      84179922        .       C       <DUP>   40      PASS    SAMPLE=T7-75_chr11;TYPE=DUP;DP=110;VD=2;AF=0.0182;BIAS=2:0;REFBIAS=27:18;VARBIAS=2:0;PMEAN=51;PSTD=1;QUAL=40.1;QSTD=1;SBF=0.51711;ODDRATIO=0;MQ=255;SN=4;HIAF=0.0435;ADJAF=0.0182;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=2;HICOV=46;LSEQ=GGTCCCTGCGTGCCGCCAGC;RSEQ=ATGAGGTGAGAAGAATTGCT;DUPRATE=0;SVTYPE=DUP;SVLEN=15760;SPLITREAD=2;SPANPAIR=0    GT:DP:VD:AD:AF:RD:ALD   0/1:110:2:45,2:0.0182:27,18:2,0


Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment] 2019-07-16 09:53
Hi Hamdi,

For some reason BAM cannot be loaded, its loading is interrupted after 4-5 hours. Can you please cut parts from this BAM with samtools, to reduce the file size? For example, for these two variants, you can cut regions chr10:11290000-11297000 and chr11:84179000-84198000 in 2 BAM files.
Thank you!

**Comment by thkitapci** [comment] 2019-07-16 16:46
Hi @PolinaBevad,
If you are trying to download the file from the cyverse link I send it might have some problems with connection. 

You can download any subsection of a BAM file directly from the UCSC genome browser (for small section usually it can be downloaded very fast)  

To do this you can click on the link: https://genome.ucsc.edu/s/thkitapci/Mouse_T7_10_11291573_VCF_BAM

Then click on My data -> Custom Tracks 

Choose the BAM file and select "View in Table Browser" on the left and click go

Select ALL fields and click "Get Output"

This way you can download any subsection from any of the BAM and VCF files present in the genome browser track for the debugging 

I am attaching here the two regions you requested for your convenience


[T7-75_Chr10_11290000_11297000.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/3398148/T7-75_Chr10_11290000_11297000.gz)


[T7-75_Chr11_84179000_84198000.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/3398153/T7-75_Chr11_84179000_84198000.gz)


If you have any trouble downloading/accessing these files let me know and I will try to figure out another method to send you the files 

Thanks
Hamdi

**Comment by PolinaBevad** [comment] 2019-07-17 11:13
Hamdi, hello!

Thank you for the detailed explanation about UCSC data! 

I downloaded these parts and I think that the chr11:84179922 DUP are really presented in samples but because of very long introns, it is hard to see them. I used IGV which can color unmatched parts to find them.

This region in T7-75 sample has soft-clips in 2 reads (J00153:248:HWMWHBBXX:2:1113:7080:21149,
J00153:248:HWMWHBBXX:2:1105:5416:46153) and these soft-clip parts are a duplicate of part of reference starting from the chr11:84195633 and ended in chr11:84195683. The SV length also included the length of introns.
In sample T7-68 I also saw the same situation in reads J00153:248:HWMWHBBXX:2:2120:6238:33440 (with mate) and J00153:248:HWMWHBBXX:2:2116:5254:4901.

SNP in these positions will be also outputted because VarDict doesn't exclude variants if there is the intersection between reads: part of reads can be a cause for one variant and one part of reads to another variant. Variants can only be combined to MNV if possible. These cases are exactly the same, DUPs appeared only in 2-4 reads, so their frequencies are quite small.

As for the DP and VD values of DEL SV variant, I will investigate the problem further.

**Comment by thkitapci** [comment] 2019-07-17 17:37
Hi @PolinaBevad,
Thanks for the information. Can you please share the screenshot of your IGV ? Also can you explain how did you visualize this on IGV so I can try to replicate it. Do you think can I change any setting on UCSC genome browser to visualize the DUP ?

Verifying the DEL is really important for my analysis because that is the strongest signal I have. I will appreciate the results of your investigation on this issue. 

Thanks!

**Comment by PolinaBevad** [comment] 2019-07-18 06:32
Hi Hamdi,

I'm still looking at the reasons for the issue with DEL SV.
About DUP: I didn't see the options to visualize this in UCSC, but in IGV it can be like this. There are 2 screenshots from IGV on T7-75 sample. First one contains 2 soft-clip ends (at the beginning of DUP), they are painted: 
![1](https://user-images.githubusercontent.com/32058078/61434304-41e36980-a93e-11e9-9496-f3bc9de960fe.PNG)

And I highlighted part of the reference that is identical to those soft-clips here (at the end of the DUP): 
![2](https://user-images.githubusercontent.com/32058078/61434343-56bffd00-a93e-11e9-94a6-a1e3a3550f3c.PNG)

**Comment by thkitapci** [comment] 2019-07-18 16:28
Hi @PolinaBevad ,
Thanks for sharing the pictures. I will try to replicate them.

One more question Is there a best practice suggestion on how to generate the bam file to be used as input for vardict ? GATK has a RNA best practice suggestions I wonder if you guys have something similar and also I wonder if the problem I have might be related to this ? I will appreciate your comment on this.

Thanks
Best Regards
Hamdi

**Comment by thkitapci** [comment] 2019-07-24 17:51
@PolinaBevad ,
Do you have any update on this issue ? 

Thanks!
Hamdi

**Comment by PolinaBevad** [comment] 2019-07-25 07:21
Hi Hamdi,

Sorry for the late reply, I was trying to found out the problem. For now, I know, that the VD for this DEL must be smaller, maximum 9, and it mustn't be a significant signal, because AD will be about 0.007. Because of introns, some coverages are calculated wrong. If you run VarDict only on the region with this DEL (chr10:11291570-11295220), then the VD will be closer to the real one. I think it will take more time to find how it is better to fix this case with introns and not to break other functionality... 

About your generation BAM question: the best practices are mostly the same as in GATK: https://docs.google.com/file/d/0B2dK2q40HDWeaGVrbE1GVV9SQkE/preview So it is better to clean, sort and validate SAM/BAM, and also to cut adaptors (with Trimmomatic, for example). We have an option to exclude adaptors from realignment, but there was found one issue when there a lot of adaptors in a sample. But we don't recommend GATK recalibration, realignment, spliced alignment splitting and so on, because VarDict is created to use the raw data for the better quality of variant calling.

**Comment by thkitapci** [comment] 2019-07-27 00:23
Hi @PolinaBevad ,
Thanks for the link to the gatk but there are multiple best practices for gatk. DNA-seq and RNA-seq requires slightly different pre-processing steps. 

Here is the suggestion for gatk4 RNA-seq: https://software.broadinstitute.org/gatk/best-practices/workflow?id=11164

For vardict are there different pre-processing requirements for different input types (DNA-seq, exome, RNA-seq) or is vardict method robust enough to handle different input types with the same pre-processing step(s)?

 For eample "SplitNCigarReads" is a specific pre-processing step in gatk4 pipeline for RNA-seq. Do you have any RNA-seq specific pre-processing step(s) for vardict ?


Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment] 2019-07-30 07:17
Hamdi, hello!

No, for RNA-Seq you don't need to add any pre-processing steps from GATK recommendations: SplitNCigarReads, ReassignOneMappingQuality, and others are specific only for GATK pipeline.

What you can do for the pre-processing is also trimming reads if needed. In post-processing of vardict result in RNA-Seq we typically increase the minimum high-quality variant depth by adding `-v 50` option while running var2vcf_valid.pl or var2vcf_paired.pl.

**Comment by PolinaBevad** [comment] 2019-09-17 08:23
Hamdi. hello! 

We merged a fix that updates frequencies in the case like this DEL SV. VD here will be smaller, then the previous, so the variant won't be significant.
I'll close this issue, but if you will have any questions, please, reopen it!

**Closed by PolinaBevad** 2019-09-17 08:23 UTC
