### ISSUE TITLE
VarDictJava 1.5.8 call false positive somatic mutations out from same "REF" and "ALT" bases

### ISSUE THREAD

**Issue by Chitanda-Satou** [AstraZeneca-NGS/VarDictJava#169] opened 2018-11-09 08:37 UTC
Greetings. 
I have met this kind of error when doing liftover VCF from hg19 to GRCH37 using GATK.
```
- htsjdk.tribble.TribbleException: **The provided VCF file is malformed at approximately line number 5453**: Duplicate allele added to VariantContext: T, for input source: file:///...xxx_T1_vardict.pass.vcf.gz

- htsjdk.tribble.TribbleException: **The provided VCF file is malformed at approximately line number 17797**: Duplicate allele added to VariantContext: T, for input source: file:///...yyy_T1_vardict.pass.vcf.gz
```
If we check the VCF files, we can found the 5453th line of xxx_T1_vardict.pass.vcf.gz is as follows:
````
**5453 chr2    45904989        .       T       T       107.0   PASS**    STATUS=StrongSomatic;SAMPLE=xxx_T1;TYPE=SNV;DP=15;VD=15;AF=1;SHIFT3=0;MSI=3.000;MSILEN=1;SSF=0;SOR=Inf;LSEQ=AGAGACACAACCGCTTCAGA;RSEQ=GGGCAGTGAAAAAGACGATG GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM        1/1:15:15:8,7:0,0:0,15:1:0,2:36.5:1:27.4:1:1:0:60:14:1:0:0.4    0/0:23:0:0,0:11,12:23,0:0:2,0:32.5:1:27.6:1:1:0:60:46:1:0:0.1
5454 chr2    46706766        .       G       A       29.0    PASS    STATUS=StrongSomatic;SAMPLE=xxx_T1;TYPE=SNV;DP=8;VD=2;AF=0.25;SHIFT3=1;MSI=3.000;MSILEN=1;SSF=0.11067;SOR=Inf;LSEQ=ATGATGGAAGCCCGGGGTGC;RSEQ=GGAGAAAGTTGCCCGACCTT  GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM        0/1:8:2:1,1:3,3:6,2:0.25:2,2:45:1:29:1:1:1:60:4:0.25:0:1        0/0:15:0:0,0:7,8:15,0:0:2,0:21.5:1:31.7:1:1:0:60:14:1:0:0.1
````

Furthermore, check the bam files of the control and tumor samples of xxx, the base at chr2:45904989 are exactly T & T.

I have find this type of error in several samples. They are:

sample | CHROM | POS | REF | ALT | DP | AF
-- | -- | -- | -- | -- | -- | --
2 | chr2 | 45904989 | T | T | 15 | 1
2 | chr2 | 95540551 | C | C | 8 | 1
2 | chr2 | 176995592 | T | T | 15 | 1
3 | chr2 | 55444952 | T | T | 33 | 1
3 | chr2 | 224831648 | T | T | 36 | 0.9722
4 | chr2 | 171400497 | T | T | 33 | 0
4 | chr2 | 179642650 | G | G | 58 | 0
6 | chr2 | 3341871 | A | A | 47 | 0
6 | chr2 | 10927522 | C | C | 58 | 1
6 | chr2 | 44184564 | G | G | 36 | 0.9722
6 | chr2 | 74755961 | A | A | 113 | 0
6 | chr2 | 99412693 | T | T | 73 | 0
6 | chr2 | 131100526 | T | T | 150 | 0
6 | chr2 | 170361092 | A | A | 21 | 0
6 | chr2 | 179474457 | A | A | 70 | 0
6 | chr2 | 210704085 | A | A | 135 | 0
7 | chr2 | 15768772 | C | C | 36 | 0
7 | chr2 | 55403002 | A | A | 65 | 0
7 | chr2 | 74781938 | C | C | 185 | 0
7 | chr2 | 179451937 | T | T | 73 | 1
8 | chr2 | 20867120 | G | G | 18 | 0
8 | chr2 | 238969768 | C | C | 31 | 0
9 | chr2 | 9048798 | A | A | 6 | 1
9 | chr2 | 31489248 | G | G | 10 | 1
9 | chr2 | 173292370 | G | G | 6 | 0
10 | chr2 | 71816733 | T | T | 46 | 0
10 | chr12 | 14827568 | T | T | 48 | 0
10 | chr17 | 39595489 | T | T | 105 | 1

Any idea about it?

**Comment by Chitanda-Satou** [comment] 2018-11-09 12:33
@PolinaBevad 
Of course yes. Could you tell me how to make the  files you want? I'm sorry  I don't quite understand what this means. *^o^*

**Comment by PolinaBevad** [comment] 2018-11-09 14:50
@Chitanda-Satou, of course. The simplest way is to use `samtools` utility. It can be installed on linux systems from the packages, please look to the docs here: http://www.htslib.org/download/ 

To cut part of bam file with it you can use such command:
`samtools view -hb initial.bam chrX:start-end > result.part.bam`
Here `-h` means you want to add header to result bam, `-b` set the output format to BAM file, and `> result.part.bam` will create new file instead of outputting result to console. You can set the region to extract like `chr2:45904900-45904550`. I think this region will be enough to extract to get the variant from the first string of sample 2 in your table. 
After you exctract it, you have to make index by `samtools index result.part.bam`. 

You can check if the VarDict determine the needed variant by using this cutted bam. If everything is ok, you can send me this bam by email polina_bevad@epam.com or you can upload it to the file storage and post the link here. 
Please, feel free to ask any questions if something goes wrong.

**Comment by PolinaBevad** [comment] 2018-11-26 11:35
@Chitanda-Satou, hello! 
I will close this issue because the problem wasn't reproduced. And as we discussed on e-mail, if you will find that it depends on some option in the command line, bed and etc, please, reopen it and we will analyze the data. 
Thank you!

**Closed by PolinaBevad** 2018-11-26 11:35 UTC
