### ISSUE TITLE
Malformed vcf, alt = ref allele

### ISSUE THREAD

**Issue by akt68** [AstraZeneca-NGS/VarDictJava#90] opened 2017-12-02 21:46 UTC
Output vcf contains entry with ALT allele equal to REF allele and genotype 0/1:
`17      41231876        .       A       A       80      q25     SAMPLE=test;TYPE=Complex;DP=145;END=41231876;VD=15;AF=0.1034;BIAS=2:2;REFBIAS=111:16;VARBIAS=11:4;PMEAN=22.5;PSTD=1;QUAL=20.7;QSTD=1;SBF=0.22873;ODDRATIO=2.50171;MQ=70;SN=2.75;HIAF=0.2444;ADJAF=0.1034;SHIFT3=0;MSI=1;MSILEN=1;NM=2.5;HICNT=11;HICOV=45;LSEQ=CTATCACCAGAACATTTAGC;RSEQ=TATAAATTCCTCTTCTTACT;GDAMP=1;TLAMP=1;NCAMP=0;AMPFLAG=0 GT:DP:VD:AD:AF:RD:ALD   0/1:145:15:127,15:0.1034:111,16:11,4`

Command line:
`VarDict -q 20 -G human_g1k_v37_decoy.fasta -b test.bam test_amplicon.bed | teststrandbias.R | var2vcf_valid.pl >test.vcf`

I have a minimal bam (222kb) and bed file (1kb) that can be used to reproduce the issue but I did not manage to upload them here. I can send them on request.

**Comment by sluke123** [comment] 2017-12-04 08:52
Sorry you are having problems. Is it possible to paste the top ~30 lines of the bedfile here?

**Comment by akt68** [comment] 2017-12-04 16:27
The minimal bed I used to reproduce the issue has only two lines. This is the complete bedfile:
`17	41231586	41231876	A1	100	+	41231609	41231850`
`17	41231760	41232032	A2	100	+	41231783	41232009`

**Comment by nkarulin** [comment] 2017-12-05 08:48
Hello, @akt68! Could you please send me those bam and bed files to reproduce the situation via email: Nikolai_Karulin@epam.com. We'll try to figure out a solution.

**Comment by nkarulin** [comment] 2017-12-06 11:42
@akt68, thank you for provided data. We have successfully reproduced the situation on the several VarDict versions including original perl version.
It seems the problem is somewhere in the local realignment part. Disabling local realignment with `-k 0` argument removes this strange vcf entry from the output.
@akt68, is this the only entry of that type you faced on the data, or there were other cases?
@zhongwulai, have you got any ideas what could influence such a behavior?

**Comment by akt68** [comment] 2017-12-11 11:53
I did see a handful of cases like this among the 850 samples in this project (amplicon sequencing with Fluidigm Juno library prep, ~1000 amplicons). Unfortunately, I deleted the whole analysis and reran with different settings and added a filter to remove entries with REF eq ALT so I don't have any other examples saved or notes on which samples / variants were affected.

**Comment by nkarulin** [comment] 2017-12-21 13:45
@akt68, don't you mind to have a look at https://github.com/AstraZeneca-NGS/VarDictJava/pull/91 PR and give it a try. There is a small fix, which removes the strange alt = ref allele from the data you have provided.

**Comment by PolinaBevad** [comment] 2018-09-11 16:29
@akt68, hello!
We made some changes in realignment and this variant doesn't appear in results now. The changes are in `master` branch of VarDictJava, but not in releases (you can build new version yourself or wait for release). 
I will close the issue, but you can reopen it if you have any questions about this topic.

**Closed by PolinaBevad** 2018-09-11 16:29 UTC
